import type { FastifyInstance } from 'fastify'
import { z } from 'zod'
import { db } from '../db.js'
import { config } from '../config.js'
import { requireAuth } from '../auth.js'
import { generateQwenText,isQwenModel,LlmConfigurationError,LlmRequestError,QWEN_MODELS,type LlmMessage } from '../llm/qwen.js'

const chatSchema=z.object({message:z.string().trim().min(1).max(8000),conversationId:z.string().uuid().optional().nullable(),model:z.string().optional(),context:z.object({page:z.string().max(50).optional(),pageTitle:z.string().max(100).optional()}).optional()})
const idSchema=z.object({id:z.string().uuid()})
const systemPrompt=`你是“销途 AI”，服务于国内 B2B 销售团队的 CRM 助手。请使用简洁、准确的中文回答。你可以帮助用户分析线索、客户、商机、报价和采集商品，但不得声称已经执行任何写操作；需要修改业务数据时，应明确说明需要用户确认。不要编造系统中不存在的数据。`

export async function aiRoutes(app:FastifyInstance){
  app.get('/models',{preHandler:requireAuth},async()=>({data:{provider:'qwen',configured:Boolean(config.DASHSCOPE_API_KEY),defaultModel:config.QWEN_DEFAULT_MODEL,models:QWEN_MODELS}}))
  app.get('/conversations/:id/messages',{preHandler:requireAuth},async(request,reply)=>{const id=idSchema.safeParse(request.params);if(!id.success)return reply.code(400).send({error:'VALIDATION_ERROR'});const conversation=await db.query('SELECT id,title,model_name,created_at,updated_at FROM ai_conversations WHERE id=$1 AND tenant_id=$2 AND user_id=$3',[id.data.id,request.authUser.tenantId,request.authUser.sub]);if(!conversation.rows[0])return reply.code(404).send({error:'NOT_FOUND'});const messages=await db.query(`SELECT id,role,content,input_tokens,output_tokens,latency_ms,created_at FROM ai_messages WHERE conversation_id=$1 AND role IN ('user','assistant') ORDER BY created_at,id`,[id.data.id]);return{data:{conversation:conversation.rows[0],messages:messages.rows}}})
  app.post('/chat',{preHandler:requireAuth},async(request,reply)=>{const input=chatSchema.safeParse(request.body);if(!input.success)return reply.code(400).send({error:'VALIDATION_ERROR',message:'消息格式不正确。',details:input.error.flatten()});const requested=input.data.model??config.QWEN_DEFAULT_MODEL;if(!isQwenModel(requested))return reply.code(400).send({error:'UNSUPPORTED_MODEL',message:'所选模型不在允许列表中。'});const client=await db.connect();let conversationId=input.data.conversationId??null;try{await client.query('BEGIN');if(conversationId){const exists=await client.query('SELECT id FROM ai_conversations WHERE id=$1 AND tenant_id=$2 AND user_id=$3 FOR UPDATE',[conversationId,request.authUser.tenantId,request.authUser.sub]);if(!exists.rows[0]){await client.query('ROLLBACK');return reply.code(404).send({error:'NOT_FOUND',message:'对话不存在。'})}await client.query('UPDATE ai_conversations SET model_provider=$2,model_name=$3,updated_at=now() WHERE id=$1',[conversationId,'qwen',requested])}else{conversationId=(await client.query(`INSERT INTO ai_conversations(tenant_id,user_id,title,context_type,model_provider,model_name)VALUES($1,$2,$3,$4,'qwen',$5)RETURNING id`,[request.authUser.tenantId,request.authUser.sub,input.data.message.slice(0,80),input.data.context?.page??'global',requested])).rows[0].id}await client.query(`INSERT INTO ai_messages(conversation_id,role,content)VALUES($1,'user',$2)`,[conversationId,input.data.message]);await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}
    const history=await db.query<{role:'user'|'assistant';content:string}>(`SELECT role,content FROM ai_messages WHERE conversation_id=$1 AND role IN ('user','assistant') ORDER BY created_at DESC,id DESC LIMIT 20`,[conversationId]);const messages:LlmMessage[]=[{role:'system',content:`${systemPrompt}\n当前页面：${input.data.context?.pageTitle||input.data.context?.page||'全局工作台'}`},...history.rows.reverse()];const started=Date.now();try{const result=await generateQwenText({messages,model:requested});const saved=(await db.query(`INSERT INTO ai_messages(conversation_id,role,content,input_tokens,output_tokens,latency_ms)VALUES($1,'assistant',$2,$3,$4,$5)RETURNING id,role,content,input_tokens,output_tokens,latency_ms,created_at`,[conversationId,result.content,result.inputTokens,result.outputTokens,Date.now()-started])).rows[0];await db.query('UPDATE ai_conversations SET updated_at=now() WHERE id=$1',[conversationId]);await db.query(`INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,after_data,request_id)VALUES($1,$2,'ai.chat','ai_conversation',$3,$4,$5)`,[request.authUser.tenantId,request.authUser.sub,conversationId,JSON.stringify({provider:'qwen',model:result.model,inputTokens:result.inputTokens,outputTokens:result.outputTokens}),request.id]);return{data:{conversationId,message:saved,model:result.model}}}catch(error){request.log.error(error);if(error instanceof LlmConfigurationError)return reply.code(503).send({error:'LLM_NOT_CONFIGURED',message:error.message});if(error instanceof LlmRequestError){const status=error.status===429?429:error.status===504?504:502;return reply.code(status).send({error:'LLM_REQUEST_FAILED',message:error.message})}throw error}
  })
}
