import { useCallback, useEffect, useState } from 'react'
import { AlertCircle, Check, Link2, LoaderCircle, RefreshCw, Unlink } from 'lucide-react'
import { getProducts, type Product } from './api'
import { getListingComparison, saveListingBinding, type ListingComparison } from './1688Api'

const names={equal:'一致',changed:'不同',unknown:'待核对'}
const time=(value:string)=>new Date(value).toLocaleString('zh-CN')
export default function ListingComparisonPanel({id,snapshotVersion,canManage,saved,onBusy}:{id:string;snapshotVersion:string;canManage:boolean;saved:()=>void;onBusy:(busy:boolean)=>void}){
  const [candidate,setCandidate]=useState<ListingComparison|null>(null)
  const [report,setReport]=useState<ListingComparison|null>(null),[products,setProducts]=useState<Product[]>([]),[selected,setSelected]=useState(''),[bindings,setBindings]=useState<Record<string,string>>({}),[editing,setEditing]=useState(false),[confirmed,setConfirmed]=useState(false),[unlink,setUnlink]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const result=(await getListingComparison(id)).data;setReport(result);setCandidate(null);setSelected(result.listing.productId||'');setBindings(Object.fromEntries(result.bindings.map(b=>[b.specId,b.variantId])));setConfirmed(false);setEditing(false);setUnlink(false)}catch(cause){setError(cause instanceof Error?cause.message:'无法读取关联资料。')}finally{setLoading(false)}},[id,snapshotVersion])
  useEffect(()=>{void load()},[load])
  async function edit(){setBusy(true);onBusy(true);try{setProducts((await getProducts({status:'active'})).data);setEditing(true);setCandidate(null);setSelected(report?.listing.productId||'');setBindings(Object.fromEntries((report?.bindings||[]).map(b=>[b.specId,b.variantId])));setConfirmed(false);setUnlink(false)}catch(cause){setError(cause instanceof Error?cause.message:'正式产品加载失败。')}finally{setBusy(false);onBusy(false)}}
  async function choose(productId:string){setSelected(productId);setBindings({});setConfirmed(false);setCandidate(null);setError('');if(!productId)return;setBusy(true);onBusy(true);try{setCandidate((await getListingComparison(id,productId)).data)}catch(cause){setSelected('');setError(cause instanceof Error?cause.message:'无法读取正式规格。')}finally{setBusy(false);onBusy(false)}}
  async function save(productId:string|null){if(!report)return;setBusy(true);onBusy(true);setError('');try{await saveListingBinding(id,{productId,revision:report.listing.bindingRevision,syncedAt:report.listing.syncedAt,confirmed:true,bindings:productId?Object.entries(bindings).filter(([,value])=>value).map(([specId,variantId])=>({specId,variantId})):[]});setEditing(false);setUnlink(false);setConfirmed(false);await load();saved()}catch(cause){setError(cause instanceof Error?cause.message:'关联保存失败。')}finally{setBusy(false);onBusy(false)}}
  return <section className="shop-comparison" aria-label="CRM 关联与差异"><div className="shop-sku-heading"><h3>CRM 关联与差异</h3><div className="shop-row-actions"><button title="刷新本地对比" aria-label="刷新本地对比" disabled={loading||busy} onClick={()=>void load()}><RefreshCw size={16}/></button>{canManage&&<button title="关联正式产品" aria-label="关联正式产品" disabled={loading||busy} onClick={()=>void edit()}><Link2 size={17}/></button>}</div></div>
    {loading&&<p className="shop-note"><LoaderCircle size={16} className="spin"/>正在读取关联资料…</p>}
    {error&&<p className="shop-local-error" role="alert"><AlertCircle size={16}/>{error}</p>}
    {report&&!loading&&<><div className="shop-comparison-context"><strong>{report.product?`${report.product.sku} · ${report.product.name}`:report.listing.productId?'关联产品已删除':'尚未关联正式产品'}</strong><small>平台快照 {time(report.listing.syncedAt)}{report.product?` · CRM 更新 ${time(report.product.updatedAt)}`:''}</small></div>
      {editing&&<div className="shop-binding-form"><label>正式产品<select aria-label="关联正式产品选择" value={selected} disabled={busy||Boolean(report.listing.productId)} onChange={e=>void choose(e.target.value)}><option value="">选择正式产品</option>{products.map(product=><option key={product.id} value={product.id}>{product.sku} · {product.name}</option>)}</select></label>{(candidate||report.listing.productId)&&<SkuBindingInputs report={candidate||report} bindings={bindings} change={next=>{setBindings(next);setConfirmed(false)}} disabled={busy}/>}<label className="shop-review-check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>确认保存本地产品关联及 SKU 对应关系</label><div className="shop-inline"><button className="shop-button" disabled={busy} onClick={()=>setEditing(false)}>取消</button><button className="shop-button primary" disabled={busy||!selected||!confirmed} onClick={()=>void save(selected)}><Check size={16}/>保存关联</button>{report.listing.productId&&<button className="shop-button danger" disabled={busy} onClick={()=>{setUnlink(true);setConfirmed(false)}}><Unlink size={16}/>解除关联</button>}</div>{unlink&&<div className="shop-publish-review"><p>解除 {report.product?.sku||'现有产品'} 的本地关联及 SKU 对应关系，保留双方商品。</p><button className="shop-button danger" disabled={busy} onClick={()=>void save(null)}><Unlink size={16}/>确认解除关联</button></div>}</div>}
      {report.product&&<><div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>字段</th><th>CRM</th><th>平台快照</th><th>对比</th></tr></thead><tbody>{([['title','商品标题'],['image','主图地址'],['basePrice','基础单价 · 人民币']] as const).map(([key,label])=><tr key={key}><td>{label}</td><td className="shop-difference-value">{report.fields[key].crm??'—'}</td><td className="shop-difference-value">{report.fields[key].platform??'—'}</td><td><Difference value={report.fields[key].status}/></td></tr>)}</tbody></table></div><p className="shop-note">{report.fields.basePrice.basis}</p><div className="shop-difference-summary"><span>已匹配 {report.summary.mapped}</span><span>价格不同 {report.summary.changedPrice}</span><span>库存不同 {report.summary.changedStock}</span><span>待核对 {report.summary.unknown}</span><span>CRM 未匹配 {report.summary.unmatchedCrm}</span><span>平台未匹配 {report.summary.unmatchedPlatform}</span></div>{report.rows.length>0&&<div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>CRM / 平台规格</th><th>CRM 单价</th><th>平台单价</th><th>价格</th><th>CRM 库存</th><th>平台库存</th><th>库存</th></tr></thead><tbody>{report.rows.map(row=><tr key={row.specId}><td><strong>{row.crmLabel}</strong><small>{row.platformLabel}</small><small>{row.specId}</small></td><td>{row.price.crm??'—'}</td><td>{row.price.platform??'—'}</td><td><Difference value={row.price.status}/></td><td>{row.stock.crm??'—'}</td><td>{row.stock.platform??'—'}</td><td><Difference value={row.stock.status}/></td></tr>)}</tbody></table></div>}</>}
    </>}
  </section>
}
function Difference({value}:{value:'equal'|'changed'|'unknown'}){return <span className={`shop-status ${value==='equal'?'positive':value==='changed'?'warning':''}`}>{names[value]}</span>}
function SkuBindingInputs({report,bindings,change,disabled}:{report:ListingComparison;bindings:Record<string,string>;change:(bindings:Record<string,string>)=>void;disabled:boolean}){return <div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>平台规格</th><th>CRM 规格</th></tr></thead><tbody>{report.platformSkus.map((sku,index)=><tr key={sku.specId||index}><td>{sku.label}<small>{sku.specId||'缺少平台 specId'}</small></td><td><select aria-label={`平台 SKU 对应 ${index+1}`} disabled={disabled||!sku.specId} value={sku.specId?bindings[sku.specId]||'':''} onChange={e=>{if(sku.specId)change({...bindings,[sku.specId]:e.target.value})}}><option value="">未匹配</option>{report.variants.map(variant=><option key={variant.id} value={variant.id} disabled={Object.entries(bindings).some(([specId,id])=>specId!==sku.specId&&id===variant.id)}>{variant.label}</option>)}</select></td></tr>)}</tbody></table></div>}
