import { useEffect, useState } from 'react'
import { AlertCircle, Check, ImagePlus, LoaderCircle, X } from 'lucide-react'
import { applyAgentImage, generateAgentImage, getAgentImages, type AgentImagePreview, type PublishDraft } from './1688Api'

const models=[['qwen-image-3.0','标准'],['qwen-image-3.0-pro','Pro'],['qwen-image-2.1-pro','2.1 Pro']] as const
export default function ImageStudio({draft,close,onBusy,updated}:{draft:PublishDraft;close:()=>void;onBusy:(busy:boolean)=>void;updated:(draft:PublishDraft)=>void}){
  const [mode,setMode]=useState<'generate'|'edit'>(draft.data_body.formValues.primaryPicture?.imageList?.length?'edit':'generate'),[model,setModel]=useState<string>('qwen-image-3.0'),[prompt,setPrompt]=useState(''),[sourceIndex,setSourceIndex]=useState(0),[placement,setPlacement]=useState<'replace'|'append'>('replace'),[albumId,setAlbumId]=useState(''),[consent,setConsent]=useState(false),[applyConfirm,setApplyConfirm]=useState(false),[previews,setPreviews]=useState<AgentImagePreview[]>([]),[selected,setSelected]=useState<AgentImagePreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const images=(draft.data_body.formValues.primaryPicture?.imageList||[]) as Array<{url:string}>
  const risky=(image:AgentImagePreview)=>!image.findings.length||image.findings.some(f=>!f.readable||f.watermark||f.rightsRisk||f.uncertain)
  useEffect(()=>{getAgentImages(draft.id).then(result=>{setPreviews(result.data);setSelected(result.data[0]||null)}).catch(cause=>setError(cause instanceof Error?cause.message:'预览读取失败。'))},[draft.id])
  async function generate(){setBusy(true);onBusy(true);setError('');setSelected(null);setApplyConfirm(false);try{const result=await generateAgentImage(draft.id,{revision:draft.revision,mode,model,prompt,sourceIndex:mode==='edit'?sourceIndex:undefined,confirmed:true});setSelected(result.data);setPreviews(current=>[result.data,...current])}catch(cause){setError(cause instanceof Error?cause.message:'生成失败。')}finally{setBusy(false);onBusy(false)}}
  async function apply(){if(!selected)return;setBusy(true);onBusy(true);setError('');try{const result=await applyAgentImage(draft.id,selected.id,{revision:draft.revision,albumId,placement,sourceIndex:placement==='replace'?sourceIndex:undefined,confirmed:true});updated(result.data.draft);close()}catch(cause){setError(cause instanceof Error?cause.message:'应用图片失败。')}finally{setBusy(false);onBusy(false)}}
  return <div className="dialog-layer shop-dialog"><button className="drawer-scrim" aria-label="关闭 AI 图片工作台" disabled={busy} onClick={close}/><section className="shop-modal wide" role="dialog" aria-modal="true" aria-label="AI 图片工作台"><header><h2>AI 图片工作台</h2><button title="关闭" disabled={busy} onClick={close}><X size={18}/></button></header><div className="shop-modal-body shop-image-studio">
    <div className="shop-inline" role="group" aria-label="图片模式"><button className={`shop-button ${mode==='edit'?'primary':''}`} disabled={busy||!images.length} onClick={()=>{setMode('edit');setSelected(null)}}>编辑原图</button><button className={`shop-button ${mode==='generate'?'primary':''}`} disabled={busy} onClick={()=>{setMode('generate');setSelected(null)}}>生成新图</button></div>
    <div className="shop-form-columns"><label>图像模型<select aria-label="图像模型" value={model} disabled={busy} onChange={e=>setModel(e.target.value)}>{models.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{mode==='edit'&&<label>参考原图<select aria-label="参考原图" value={sourceIndex} disabled={busy} onChange={e=>setSourceIndex(Number(e.target.value))}>{images.map((_,index)=><option key={index} value={index}>主图 {index+1}</option>)}</select></label>}</div>
    {mode==='edit'&&images[sourceIndex]&&<img className="shop-image-source" src={images[sourceIndex].url.startsWith('img/')?`https://cbu01.alicdn.com/${images[sourceIndex].url}`:images[sourceIndex].url} alt={`参考主图 ${sourceIndex+1}`} referrerPolicy="no-referrer"/>}
    <label>画面要求<textarea aria-label="画面要求" rows={4} value={prompt} maxLength={2000} disabled={busy} onChange={e=>setPrompt(e.target.value)} placeholder={mode==='edit'?'例如：保持产品结构和颜色不变，改善光线与白底质感':'例如：以已审核产品为主体，生成真实、清晰的白底商品展示图'}/></label>
    <label className="shop-review-check"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>确认拥有原图及商品使用权，并同意发送资料至阿里云百炼；生成费用按模型计费</label>
    <button className="shop-button primary" disabled={busy||prompt.trim().length<8||!consent||(mode==='edit'&&!images[sourceIndex])} onClick={()=>void generate()}>{busy?<LoaderCircle className="spin" size={16}/>:<ImagePlus size={16}/>}生成预览</button>
    {previews.length>1&&<label>历史预览<select aria-label="历史预览" value={selected?.id||''} disabled={busy} onChange={e=>setSelected(previews.find(item=>item.id===e.target.value)||null)}><option value="">选择预览</option>{previews.map(item=><option key={item.id} value={item.id}>{new Date(item.created_at).toLocaleString('zh-CN')} · {item.status==='applied'?'已应用':item.status==='applying'?'上传待核对':'待应用'}</option>)}</select></label>}
    {selected&&<div className="shop-image-preview"><img src={selected.url} alt="AI 图片预览" referrerPolicy="no-referrer"/><div><strong>{risky(selected)?'需要核对，禁止应用':'复检通过，可选择应用'}</strong><small>{selected.storage==='oss'?'已保存至私有 OSS；预览链接失效时重新打开工作台即可查看':`临时预览至 ${new Date(selected.expires_at).toLocaleString('zh-CN')}`}</small>{selected.findings.map((finding,index)=><p key={index} className={risky(selected)?'shop-local-error':'shop-note'}>{finding.reason}</p>)}</div></div>}
    {selected&&!risky(selected)&&selected.status==='preview'&&<div className="shop-image-apply"><div className="shop-form-columns"><label>店铺相册 ID<input aria-label="店铺相册 ID" value={albumId} onChange={e=>setAlbumId(e.target.value)} inputMode="numeric" pattern="[0-9]+" disabled={busy}/></label><label>应用位置<select aria-label="应用位置" value={placement} disabled={busy} onChange={e=>setPlacement(e.target.value as 'replace'|'append')}><option value="replace">替换主图</option><option value="append">追加主图</option></select></label>{placement==='replace'&&<label>替换哪张主图<select aria-label="替换哪张主图" value={sourceIndex} disabled={busy} onChange={e=>setSourceIndex(Number(e.target.value))}>{images.map((_,index)=><option key={index} value={index}>主图 {index+1}</option>)}</select></label>}</div><label className="shop-review-check"><input type="checkbox" checked={applyConfirm} disabled={busy} onChange={e=>setApplyConfirm(e.target.checked)}/>确认上传至店铺相册并更新本地发布草稿；不会直接发布商品</label><button className="shop-button primary" disabled={busy||!applyConfirm||!/^\d{1,20}$/.test(albumId)||(placement==='replace'&&!images[sourceIndex])} onClick={()=>void apply()}><Check size={16}/>上传并应用</button></div>}
    {error&&<p role="alert" className="shop-local-error"><AlertCircle size={16}/>{error}</p>}
  </div><footer><button className="shop-button" disabled={busy} onClick={close}>关闭</button></footer></section></div>
}
