import DeleteListing from './1688DeleteListing'
import LogisticsEditor from './1688LogisticsEditor'
import { applyDraftTemplate } from './1688Api'
import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import './1688.css'
import SkuEditor from './1688SkuEditor'
import ListingComparisonPanel from './1688ListingComparison'
import AgentPanel from './1688AgentPanel'
import { AlertCircle, CheckCircle2, ChevronLeft, ChevronRight, ExternalLink, FilePlus2, ImagePlus, Link2, LoaderCircle, Package, Plus, Power, RefreshCw, Save, Search, Send, ShieldCheck, Store, Trash2, X } from 'lucide-react'
import { getProducts, type Product, type SessionUser } from './api'
import { getAgentSettings, runPublishingAgent, completeShopAuthorization, createPublishDraft, disableShopConnection, findShopCategories, getPublishDraft, getPublishDrafts, getShopConnections, getShopListing, getShopListings, getShopOperations, reconcilePublishDraft, refreshShopListing, refreshShopToken, savePublishDraft, startShopAuthorization, submitPublishDraft, syncShopPage, testShopConnection, updateShopStock, uploadShopPhoto, type CategoryOption, type IntegrationOperation, type PlatformListing, type PublishDraft, type ShopConnection } from './1688Api'

const imageUrl=(value:string)=>value.startsWith('img/')?`https://cbu01.alicdn.com/${value}`:value
const time = (value:string|null) => value ? new Date(value).toLocaleString('zh-CN') : '—'
const message = (cause:unknown) => cause instanceof Error ? cause.message : '操作未完成，请稍后重试。'
const statusNames:Record<string,string> = { connected:'已连接',reauthorize:'需重新授权',disabled:'已停用',draft:'待补全',submitting:'提交中',published:'已发布',failed:'失败',unknown:'待核对',PUBLISHED:'已发布',expired:'已下架','member expired':'会员到期',deleted:'已删除',auditing:'审核中',available:'可用',unavailable:'不可用',success:'成功' }
const permission = (user:SessionUser,name:string) => (user.permissions||[]).some(value => value==='*'||value===name||value===`${name.split(':')[0]}:*`)

function Modal({title,children,close,wide=false}:{title:string;children:ReactNode;close:()=>void;wide?:boolean}) {
  useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')close()};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[close])
  return <div className="dialog-layer shop-dialog"><button className="drawer-scrim" onClick={close} aria-label="关闭对话框"/><section role="dialog" aria-modal="true" aria-label={title} className={wide?'shop-modal wide':'shop-modal'}><header><h2>{title}</h2><button title="关闭" onClick={close}><X size={18}/></button></header>{children}</section></div>
}

export default function Integration1688Page({user,onCollections}:{user:SessionUser;onCollections:()=>void}) {
  const [view,setView]=useState<'connections'|'listings'|'drafts'|'operations'>('listings')
  const [connections,setConnections]=useState<ShopConnection[]>([]),[selected,setSelected]=useState(''),[configured,setConfigured]=useState(false)
  const [listings,setListings]=useState<PlatformListing[]>([]),[drafts,setDrafts]=useState<PublishDraft[]>([]),[operations,setOperations]=useState<IntegrationOperation[]>([])
  const [search,setSearch]=useState(''),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const [authUrl,setAuthUrl]=useState(''),[callbackUrl,setCallbackUrl]=useState(''),[disable,setDisable]=useState<ShopConnection|null>(null),[create,setCreate]=useState(false),[draft,setDraft]=useState<PublishDraft|null>(null),[listing,setListing]=useState<PlatformListing|null>(null)
  const canManage=permission(user,'integration:manage'),canPublish=permission(user,'integration:publish'),canRead=permission(user,'integration:read')
  const syncAbort=useRef(false)
  useEffect(()=>()=>{syncAbort.current=true},[])
  const load=useCallback(async()=>{
    if(!canRead){setLoading(false);return}
    setLoading(true);setError('')
    try {
      const shop=await getShopConnections();setConnections(shop.data);setConfigured(shop.configured)
      const id=shop.data.some(c=>c.id===selected)?selected:shop.data[0]?.id||''
      if(id!==selected){setSelected(id);return}
      if(view==='listings')setListings(id?(await getShopListings(id,page,search)).data:[])
      if(view==='drafts')setDrafts((await getPublishDrafts()).data)
      if(view==='operations')setOperations((await getShopOperations(page)).data)
    } catch(cause){setError(message(cause))} finally {setLoading(false)}
  },[canRead,selected,view,page,search])
  useEffect(()=>{void load()},[load])
  async function action(name:string,run:()=>Promise<unknown>,success:string){setBusy(name);setError('');try{await run();setNotice(success);await load()}catch(cause){setError(message(cause))}finally{setBusy('')}}
  async function authorize(){setBusy('authorize');setError('');try{const result=await startShopAuthorization();setAuthUrl(result.data.authorizationUrl);setCallbackUrl('')}catch(cause){setError(message(cause))}finally{setBusy('')}}
  async function sync(){if(!selected)return;syncAbort.current=false;setBusy('sync');setError('');let count=0;try{let hasMore=true;for(let index=1;hasMore&&!syncAbort.current;index++){if(index>1000)throw new Error('本轮同步达到分页上限，请联系管理员继续。');const result=await syncShopPage(selected,index);count+=result.data.count;hasMore=result.data.hasMore;setNotice(`正在同步 ${count} / ${result.data.total||'—'} 件商品`)}setNotice(syncAbort.current?`同步已停止，本轮已读取 ${count} 件`:`同步完成，本轮已读取 ${count} 件`);await load()}catch(cause){setError(`${message(cause)} 本轮已读取 ${count} 件，已保存的数据可继续查看。`);await load()}finally{setBusy('')}}
  async function openDraft(id:string){setBusy(id);try{setDraft((await getPublishDraft(id)).data)}catch(cause){setError(message(cause))}finally{setBusy('')}}
  async function openListing(id:string){setBusy(id);try{setListing((await getShopListing(id)).data)}catch(cause){setError(message(cause))}finally{setBusy('')}}
  if(!canRead)return <section className="state-card"><ShieldCheck size={28}/><h2>暂无店铺访问权限</h2></section>
  return <div className="shop-workspace">
    <div className="shop-toolbar"><nav className="shop-tabs" aria-label="1688 店铺视图">{([['listings','平台商品'],['drafts','发布工作台'],['connections','连接设置'],['operations','同步记录']] as const).map(([id,label])=><button key={id} aria-current={view===id?'page':undefined} className={view===id?'active':''} onClick={()=>{setView(id);setPage(1)}}>{label}</button>)}</nav><button className="shop-button" onClick={onCollections}><Package size={16}/>采集商品</button></div>
    {notice&&<div className="shop-feedback" role="status"><CheckCircle2 size={16}/><span>{notice}</span><button title="关闭提示" onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {error&&<div className="shop-feedback error" role="alert"><AlertCircle size={16}/><span>{error}</span><button title="关闭错误" onClick={()=>setError('')}><X size={15}/></button></div>}
    <div className="shop-controlbar"><div className="shop-select"><Store size={17}/><select aria-label="目标店铺" value={selected} disabled={Boolean(busy)} onChange={e=>{setSelected(e.target.value);setPage(1)}}><option value="">选择店铺</option>{connections.map(c=><option key={c.id} value={c.id}>{c.display_name} · {statusNames[c.status]}</option>)}</select></div><div className="shop-commandbar">
      {view==='listings'&&<><div className="shop-search"><Search size={16}/><input aria-label="搜索平台商品" value={search} placeholder="商品标题或 ID" onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div>{canManage&&<button className="shop-button primary" disabled={Boolean(busy)||!selected||connections.find(c=>c.id===selected)?.status!=='connected'} onClick={()=>void sync()}><RefreshCw size={16} className={busy==='sync'?'spin':''}/>{busy==='sync'?'正在同步':'同步店铺'}</button>}{busy==='sync'&&<button className="shop-button" onClick={()=>{syncAbort.current=true}}>停止</button>}</>}
      {view==='drafts'&&canPublish&&<button className="shop-button primary" disabled={!selected||Boolean(busy)} onClick={()=>setCreate(true)}><FilePlus2 size={16}/>新建草稿</button>}
      {view==='connections'&&canManage&&<button className="shop-button primary" disabled={!configured||Boolean(busy)} onClick={()=>void authorize()}><Link2 size={16}/>连接店铺</button>}
      <button className="shop-icon" title="刷新当前视图" aria-label="刷新当前视图" disabled={Boolean(busy)} onClick={()=>void load()}><RefreshCw size={17}/></button>
    </div></div>
    {loading?<div className="shop-empty"><LoaderCircle size={26} className="spin"/><p>正在读取店铺数据…</p></div>:<>
      {view==='connections'&&<div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>店铺 / 账号</th><th>连接状态</th><th>账号接口</th><th>访问令牌有效期</th><th>刷新令牌有效期</th><th>操作</th></tr></thead><tbody>{connections.map(c=><tr key={c.id}><td><strong>{c.display_name}</strong><small>{c.member_id||c.login_id}</small></td><td><Status value={c.status}/></td><td><Status value={c.member_capability}/></td><td>{time(c.access_expires_at)}</td><td>{time(c.refresh_expires_at)}</td><td><div className="shop-row-actions">{canManage&&<><button title="验证账号接口" aria-label={`验证 ${c.display_name}`} disabled={Boolean(busy)||c.status!=='connected'} onClick={()=>void action(c.id,()=>testShopConnection(c.id),'账号信息验证成功')}><ShieldCheck size={17}/></button><button title="刷新访问令牌" aria-label={`刷新 ${c.display_name} 令牌`} disabled={Boolean(busy)||c.status!=='connected'} onClick={()=>void action(c.id,()=>refreshShopToken(c.id),'访问令牌已刷新')}><RefreshCw size={17}/></button><button title="停用连接" aria-label={`停用 ${c.display_name}`} disabled={Boolean(busy)||c.status==='disabled'} onClick={()=>setDisable(c)}><Power size={17}/></button></>}</div></td></tr>)}</tbody></table>{!connections.length&&<Empty text={configured?'尚未连接店铺':'服务器尚未配置 1688 应用'}/>}</div>}
      {view==='listings'&&<div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>商品</th><th>平台 ID</th><th>CRM SKU</th><th>平台状态</th><th>同步时间</th><th/></tr></thead><tbody>{listings.map(item=><tr key={item.id}><td><div className="shop-product-cell">{item.image_url?<img src={imageUrl(item.image_url)} alt="" referrerPolicy="no-referrer"/>:<div className="shop-thumbnail"><Package size={20}/></div>}<strong>{item.title}</strong></div></td><td>{item.offer_id}</td><td>{item.sku||'未关联'}</td><td><Status value={item.status}/></td><td>{time(item.synced_at)}</td><td><button className="shop-icon" title="查看平台商品" aria-label={`查看 ${item.title}`} disabled={Boolean(busy)} onClick={()=>void openListing(item.id)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table>{!listings.length&&<Empty text={selected?'当前没有已同步商品':'请先连接店铺'}/>}</div>}
      {view==='drafts'&&<div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>正式产品</th><th>目标店铺</th><th>类目</th><th>状态</th><th>平台商品 ID</th><th/></tr></thead><tbody>{drafts.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.sku}</small></td><td>{item.display_name}</td><td>{item.cat_id}</td><td><Status value={item.status}/>{item.last_error_code&&<small>{item.last_error_code}</small>}</td><td>{item.offer_id||'—'}</td><td><button className="shop-icon" title="编辑发布草稿" aria-label={`查看草稿 ${item.name}`} disabled={Boolean(busy)} onClick={()=>void openDraft(item.id)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table>{!drafts.length&&<Empty text="暂无发布草稿"/>}</div>}
      {view==='operations'&&<div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>时间</th><th>店铺</th><th>接口 / 操作</th><th>结果</th><th>错误码</th><th>耗时</th></tr></thead><tbody>{operations.map(item=><tr key={item.id}><td>{time(item.created_at)}</td><td>{item.display_name||'—'}</td><td><code>{item.api_name}</code></td><td><Status value={item.outcome}/></td><td>{item.error_code||'—'}</td><td>{item.duration_ms} ms</td></tr>)}</tbody></table>{!operations.length&&<Empty text="暂无调用记录"/>}</div>}
    </>}
    {(view==='listings'||view==='operations')&&<div className="shop-pagination"><button className="shop-icon" title="上一页" disabled={loading||page===1||Boolean(busy)} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>第 {page} 页</span><button className="shop-icon" title="下一页" disabled={loading||Boolean(busy)||(view==='listings'?listings.length<20:operations.length<50)} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div>}
    {authUrl&&<Modal title="连接 1688 店铺" close={()=>setAuthUrl('')}><div className="shop-modal-body"><a className="shop-button primary" href={authUrl} target="_blank" rel="noreferrer">前往 1688 授权 <ExternalLink size={16}/></a><label>完整回跳地址<input value={callbackUrl} onChange={e=>setCallbackUrl(e.target.value)} autoComplete="off" placeholder="https://…?code=…&state=…"/></label><p className="shop-note">授权码有效期 2 分钟</p></div><footer><button className="shop-button" onClick={()=>setAuthUrl('')}>取消</button><button className="shop-button primary" disabled={!callbackUrl||Boolean(busy)} onClick={()=>void action('complete',async()=>{await completeShopAuthorization(callbackUrl);setAuthUrl('');setCallbackUrl('')},'店铺授权完成')}><CheckCircle2 size={16}/>完成连接</button></footer></Modal>}
    {disable&&<Modal title="停用店铺连接" close={()=>setDisable(null)}><div className="shop-modal-body"><p>{disable.display_name} 将停止发布与同步，历史记录保留。</p></div><footer><button className="shop-button" onClick={()=>setDisable(null)}>取消</button><button className="shop-button danger" disabled={Boolean(busy)} onClick={()=>void action('disable',async()=>{await disableShopConnection(disable.id);setDisable(null)},'连接已停用')}>停用连接</button></footer></Modal>}
    {create&&<CreateDraft connectionId={selected} close={()=>setCreate(false)} saved={item=>{setCreate(false);setDraft(item);void load()}}/>}
    {draft&&<DraftEditor initial={draft} targetName={connections.find(c=>c.id===draft.connection_id)?.display_name||'未知店铺'} canPublish={canPublish} close={()=>setDraft(null)} saved={()=>void load()}/>}
    {listing&&<ListingViewer initial={listing} canManage={canManage} canPublish={canPublish} close={()=>setListing(null)} saved={()=>void load()}/>}
  </div>
}

function Status({value}:{value:string}) {return <span className={`shop-status ${value==='failed'||value==='unavailable'||value==='reauthorize'?'warning':value==='connected'||value==='available'||value==='success'||value==='published'?'positive':''}`}>{statusNames[value]||value}</span>}
function Empty({text}:{text:string}) {return <div className="shop-empty"><Store size={28}/><p>{text}</p></div>}

function CreateDraft({connectionId,close,saved}:{connectionId:string;close:()=>void;saved:(draft:PublishDraft)=>void}) {
  const [products,setProducts]=useState<Product[]>([]),[productId,setProductId]=useState(''),[keyword,setKeyword]=useState(''),[categories,setCategories]=useState<CategoryOption[]>([]),[catId,setCatId]=useState(''),[scene,setScene]=useState('cbu'),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{getProducts({status:'active'}).then(result=>setProducts(result.data)).catch(cause=>setError(message(cause)))},[])
return <Modal title="新建发布草稿" close={close}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const created=(await createPublishDraft({connectionId,productId,catId,scene})).data;try{const settings=await getAgentSettings();if(settings.data.find(s=>s.id===connectionId)?.enabled)await runPublishingAgent(created.id,created.revision)}catch(cause){setError(message(cause))}saved((await getPublishDraft(created.id)).data)}catch(cause){setError(message(cause))}finally{setBusy(false)}}}><div className="shop-modal-body"><label>正式产品<select aria-label="正式产品" value={productId} onChange={e=>setProductId(e.target.value)} required><option value="">请选择已审核产品</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>搜索发布类目<div className="shop-inline"><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="产品关键词"/><button type="button" className="shop-icon" title="搜索类目" disabled={!keyword||busy} onClick={async()=>{setBusy(true);try{setCategories((await findShopCategories(connectionId,keyword)).data)}catch(cause){setError(message(cause))}finally{setBusy(false)}}}><Search size={17}/></button></div></label>{categories.length>0&&<label>类目结果<select value={catId} onChange={e=>{setCatId(e.target.value);const type=categories.find(c=>String(c.categoryID)===e.target.value)?.categoryType;if(type)setScene(type===3?'popular':type===2?'industry':'cbu')}}><option value="">请选择</option>{categories.map(c=><option key={c.categoryID} value={String(c.categoryID)}>{c.name} · {c.categoryID}</option>)}</select></label>}<div className="shop-form-columns"><label>类目 ID<input aria-label="类目 ID" required pattern="[0-9]+" value={catId} onChange={e=>setCatId(e.target.value)}/></label><label>发布场景<select value={scene} onChange={e=>setScene(e.target.value)}><option value="cbu">1688 大市场</option><option value="popular">主流商品</option><option value="industry">工业品专业化</option><option value="processing">加工定制</option></select></label></div>{error&&<p className="shop-local-error" role="alert">{error}</p>}</div><footer><button type="button" className="shop-button" onClick={close}>取消</button><button className="shop-button primary" disabled={busy||!productId||!catId}>{busy?<LoaderCircle size={16} className="spin"/>:<FilePlus2 size={16}/>}获取发布规则</button></footer></form></Modal>
}

function DraftEditor({initial,targetName,canPublish,close,saved}:{initial:PublishDraft;targetName:string;canPublish:boolean;close:()=>void;saved:()=>void}) {
  const [draft,setDraft]=useState(initial),[values,setValues]=useState<Record<string,any>>(initial.data_body.formValues),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[offerId,setOfferId]=useState(initial.offer_id||''),[albumId,setAlbumId]=useState('')
  const reviewRef=useRef<HTMLDivElement>(null)
  useEffect(()=>{if(confirm){reviewRef.current?.scrollIntoView({block:'start',behavior:'instant'});reviewRef.current?.focus({preventScroll:true})}},[confirm])
  const [invalidFields,setInvalidFields]=useState<Record<string,boolean>>({})
  const invalid=Object.values(invalidFields).some(Boolean)
  const onInvalid=(name:string,invalid:boolean)=>{setInvalidFields(current=>({...current,[name]:invalid}));setConfirm(false)}
  const editable=canPublish&&['draft','failed'].includes(draft.status)
  const change=(key:string,value:unknown)=>{setValues(current=>({...current,[key]:value}));setDirty(true);setConfirm(false)}
  async function save(){setBusy(true);setError('');try{const result=await savePublishDraft(draft.id,draft.revision,values);setDraft(result.data);setDirty(false);saved();if(result.missing.length)setError(`待补全：${result.missing.join('、')}`)}catch(cause){setError(message(cause))}finally{setBusy(false)}}
  const components=Object.entries(draft.platform_schema.data||{}).filter(([key,node])=>{const f=(node as any).fields;return f&&f.visible!==false&&f.label&&!['title','primaryPicture','description','saleProp','skuTable'].includes(key)&&!(node as any).type?.includes('layout')}) as [string,any][]
  const adopt=(result:{data:PublishDraft;missing:string[]})=>{setDraft(result.data);setValues(result.data.data_body.formValues);setDirty(false);setConfirm(false);setInvalidFields({});setError(result.missing.length?`待补全：${result.missing.join('、')}`:'');saved()}
  const images=(values.primaryPicture?.imageList||[]) as Array<{url:string}>
  return <Modal title="商品发布草稿" close={close} wide><div className="shop-editor-context"><Status value={draft.status}/><span>{targetName} · 类目 {draft.cat_id} · {draft.scene}</span>{draft.offer_id&&<a href={`https://detail.1688.com/offer/${draft.offer_id}.html`} target="_blank" rel="noreferrer">商品 {draft.offer_id} <ExternalLink size={14}/></a>}</div><div className="shop-modal-body shop-editor-fields">
    <AgentPanel draft={draft} disabled={!canPublish||busy||dirty||invalid} onBusy={setBusy} updated={async()=>{const result=await getPublishDraft(draft.id);adopt(result)}}/>
    {editable&&<button className="shop-button" disabled={busy||dirty||invalid} onClick={async()=>{setBusy(true);setError('');try{adopt(await applyDraftTemplate(draft.id,draft.revision))}catch(cause){setError(message(cause))}finally{setBusy(false)}}}>应用公共模板（仅补空值）</button>}
    <label>商品标题<input value={values.title||''} maxLength={draft.platform_schema.data?.title?.fields?.maxLength||128} disabled={!editable||busy} onChange={e=>change('title',e.target.value)}/></label>
    <div className="shop-images"><span className="shop-field-label">商品主图</span><div className="shop-image-grid">{images.map((image,index)=><div key={`${image.url}-${index}`}><img src={image.url.startsWith('img/')?`https://cbu01.alicdn.com/${image.url}`:image.url} alt={`主图 ${index+1}`} referrerPolicy="no-referrer"/>{editable&&<button title="移除主图" onClick={()=>change('primaryPicture',{...values.primaryPicture,imageList:images.filter((_,i)=>i!==index)})}><Trash2 size={14}/></button>}</div>)}</div>{editable&&<><label>相册 ID<input value={albumId} onChange={e=>setAlbumId(e.target.value)} inputMode="numeric"/></label><label className="shop-upload"><ImagePlus size={17}/>上传主图<input type="file" accept="image/jpeg,image/png,image/gif,image/bmp" disabled={!albumId||busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setError('图片不能超过 2MB');return}setBusy(true);try{const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});const photo=(await uploadShopPhoto(draft.connection_id,{albumId,name:file.name.slice(0,30),content,mime:file.type})).data;change('primaryPicture',{...values.primaryPicture,imageList:[...images,{url:photo.url}]})}catch(cause){setError(message(cause))}finally{setBusy(false)}}}/></label></>}</div>
    <label>详情描述<textarea rows={5} disabled={!editable||busy} value={values.description?.detailList?.[0]?.content||''} onChange={e=>change('description',{detailList:[{id:'0',title:'图文详情',content:e.target.value,isRequired:true}]})}/></label>
    {(draft.platform_schema.data?.saleProp||draft.platform_schema.data?.skuTable)&&<SkuEditor draft={draft} values={values} disabled={!editable||busy} unsaved={dirty||invalid} change={next=>{setValues(current=>({...current,...next}));setDirty(true);setConfirm(false)}} adopt={adopt} onBusy={setBusy}/>}
    {components.map(([key,node])=><SchemaField key={key} name={key} fields={node.fields} value={values[key]} disabled={!editable||busy||node.fields.readonly} onChange={value=>change(key,value)} onInvalid={onInvalid}/>)}
    {(draft.status==='unknown'||draft.status==='submitting')&&<div className="shop-reconcile"><p>发布结果需要核对。请填写店铺中对应商品的 ID，系统将校验归属和标题。</p><input aria-label="核对平台商品 ID" value={offerId} onChange={e=>setOfferId(e.target.value)} inputMode="numeric"/><button className="shop-button" disabled={busy||!offerId||!canPublish} onClick={async()=>{setBusy(true);try{await reconcilePublishDraft(draft.id,offerId);setDraft((await getPublishDraft(draft.id)).data);saved()}catch(cause){setError(message(cause))}finally{setBusy(false)}}}><CheckCircle2 size={16}/>核对关联</button></div>}
    {error&&<p className="shop-local-error" role="alert">{error}</p>}
    {confirm&&<div className="shop-publish-review" ref={reviewRef} tabIndex={-1} role="region" aria-label="确认发布到 1688"><h3>确认发布到 1688</h3><p>目标店铺：{targetName}</p><p>{values.title}</p><p>{images.length} 张主图 · {Array.isArray(values.skuTable)?values.skuTable.length:0} 个 SKU · 类目 {draft.cat_id} · 草稿版本 {draft.revision}</p><button className="shop-button primary" disabled={busy||dirty||invalid} onClick={async()=>{setBusy(true);setError('');try{await submitPublishDraft(draft.id,draft.revision);setDraft((await getPublishDraft(draft.id)).data);setConfirm(false);saved()}catch(cause){setError(message(cause));try{setDraft((await getPublishDraft(draft.id)).data);saved()}catch{}}finally{setBusy(false)}}}><Send size={16}/>确认提交</button></div>}
    </div><footer><button className="shop-button" onClick={close}>关闭</button>{editable&&<><button className="shop-button" disabled={!dirty||busy||invalid} onClick={()=>void save()}><Save size={16}/>保存草稿</button><button className="shop-button primary" disabled={dirty||busy||invalid} onClick={()=>{setConfirm(true);reviewRef.current?.scrollIntoView({block:'start',behavior:'instant'});reviewRef.current?.focus({preventScroll:true})}}><Send size={16}/>发布预览</button></>}</footer></Modal>
}

function SchemaField({name,fields,value,disabled,onChange,onInvalid}:{name:string;fields:any;value:any;disabled:boolean;onChange:(value:any)=>void;onInvalid:(name:string,invalid:boolean)=>void}) {
  const label=String(fields.label)+(fields.required||name==='officialLogistics'&&fields.logisticsRequired?' *':'')
  const options=Array.isArray(fields.dataSource)?fields.dataSource:[]
  if(name==='catProp')return <fieldset className="shop-property-fields"><legend>{label}</legend>{options.map((prop:any)=><SchemaField key={prop.name} name={prop.name} fields={prop} value={value?.[prop.name]} disabled={disabled||prop.readonly} onChange={next=>onChange({...value,[prop.name]:next})} onInvalid={onInvalid}/>)}</fieldset>
  if(options.length&&options.every((option:any)=>typeof option==='object'&&option!==null&&'value'in option&&'text'in option)&&fields.uiType!=='cbu_specs')return <label>{label}<select disabled={disabled} value={value?.value==null?'':String(value.value)} onChange={e=>onChange(e.target.value?options.find((option:any)=>String(option.value)===e.target.value):null)}><option value="">请选择</option>{options.map((option:any)=><option key={String(option.value)} value={String(option.value)}>{option.text}</option>)}</select></label>
  if(name==='officialLogistics'&&value?.showLogisticsCategory!=='sku')return <LogisticsEditor fields={fields} value={value} disabled={disabled} onChange={onChange}/>
  if(name==='cbuUnit')return <label>{label}<input disabled={disabled} value={value?.unit||''} onChange={e=>onChange({...value,unit:e.target.value})}/></label>
  if(fields.uiType==='cbunumber'||fields.uiType==='cbuinput'||fields.uiType==='input')return <label>{label}<input disabled={disabled} type={fields.uiType==='cbunumber'?'number':'text'} min={fields.uiType==='cbunumber'?0:undefined} step={fields.precision?10**-fields.precision:1} value={value??''} onChange={e=>onChange(fields.uiType==='cbunumber'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/></label>
  if(Array.isArray(fields.column))return <div className="shop-schema-table"><span className="shop-field-label">{label}</span><div className="shop-table-scroll"><table className="shop-table"><thead><tr>{fields.column.filter((col:any)=>col.visible!==false).map((col:any)=><th key={col.name}>{col.label}</th>)}<th/></tr></thead><tbody>{(Array.isArray(value)?value:[]).map((row:any,index:number)=><tr key={index}>{fields.column.filter((col:any)=>col.visible!==false).map((col:any)=><td key={col.name}>{col.readonly||typeof row[col.name]==='object'?<span>{Array.isArray(row[col.name])?row[col.name].map((part:any)=>part.text||part.value).join(' / '):String(row[col.name]??'—')}</span>:<input aria-label={`${col.label} ${index+1}`} disabled={disabled} type={col.uiType==='cbunumber'?'number':'text'} step={col.precision?10**-col.precision:1} value={row[col.name]??''} onChange={e=>onChange(value.map((v:any,i:number)=>i===index?{...v,[col.name]:col.uiType==='cbunumber'?(e.target.value===''?null:Number(e.target.value)):e.target.value}:v))}/>}</td>)}<td><button className="shop-icon" title="移除报价行" disabled={disabled} onClick={()=>onChange(value.filter((_:any,i:number)=>i!==index))}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>{!disabled&&<button className="shop-button" onClick={()=>onChange([...(Array.isArray(value)?value:[]),{}])}><Plus size={15}/>添加报价行</button>}</div>
  return <JsonField name={name} onInvalid={onInvalid} label={label} value={value} disabled={disabled} onChange={onChange}/>
}
function JsonField({name,label,value,disabled,onChange,onInvalid}:{name:string;label:string;value:any;disabled:boolean;onChange:(value:any)=>void;onInvalid:(name:string,invalid:boolean)=>void}) {
  const [text,setText]=useState(JSON.stringify(value??null,null,2)),[invalid,setInvalid]=useState(false)
  useEffect(()=>setText(JSON.stringify(value??null,null,2)),[value])
  return <details className="shop-extra-field"><summary>{label}{invalid&&<span> · 格式错误</span>}</summary><textarea aria-label={label} value={text} rows={5} disabled={disabled} onChange={e=>{setText(e.target.value);try{const parsed=JSON.parse(e.target.value);setInvalid(false);onInvalid(name,false);onChange(parsed)}catch{setInvalid(true);onInvalid(name,true)}}}/><small>平台扩展字段</small></details>
}

function ListingViewer({initial,canManage,canPublish,close,saved}:{initial:PlatformListing;canManage:boolean;canPublish:boolean;close:()=>void;saved:()=>void}) {
  const [listing,setListing]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[stocks,setStocks]=useState<Array<{specId:string|null;before:number;after:number}>>([]),[confirm,setConfirm]=useState(false)
  useEffect(()=>{const info=listing.snapshot;setStocks(info?.skuInfos?.length?info.skuInfos.map(s=>({specId:s.specId,before:Number(s.amountOnSale),after:Number(s.amountOnSale)})):info?.saleInfo?.amountOnSale!=null?[{specId:null,before:Number(info.saleInfo.amountOnSale),after:Number(info.saleInfo.amountOnSale)}]:[])},[listing])
  async function refresh(){setBusy(true);setError('');try{await refreshShopListing(listing.id);setListing((await getShopListing(listing.id)).data);saved()}catch(cause){setError(message(cause))}finally{setBusy(false)}}
  return <Modal title="平台商品详情" close={close} wide><div className="shop-modal-body"><div className="shop-listing-head">{listing.image_url&&<img src={imageUrl(listing.image_url)} alt="" referrerPolicy="no-referrer"/>}<div><h3>{listing.title}</h3><p>{listing.offer_id} · <Status value={listing.status}/></p><a href={`https://detail.1688.com/offer/${listing.offer_id}.html`} target="_blank" rel="noreferrer">查看平台商品 <ExternalLink size={14}/></a></div></div><ListingComparisonPanel id={listing.id} snapshotVersion={listing.synced_at} canManage={canManage} saved={saved} onBusy={setBusy}/><div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>规格标识</th><th>当前库存</th><th>目标库存</th></tr></thead><tbody>{stocks.map((stock,index)=><tr key={stock.specId||'total'}><td>{stock.specId||'商品总库存'}</td><td>{stock.before}</td><td><input aria-label={`目标库存 ${index+1}`} type="number" min="0" step="1" disabled={!canPublish||busy} value={stock.after} onChange={e=>{setStocks(current=>current.map((s,i)=>i===index?{...s,after:Number(e.target.value)}:s));setConfirm(false)}}/></td></tr>)}</tbody></table></div>{!stocks.length&&<p className="shop-note">当前快照未包含库存，请刷新商品详情。</p>}{confirm&&<div className="shop-publish-review"><h3>确认修改平台库存</h3>{stocks.filter(s=>s.before!==s.after).map(s=><p key={s.specId||'total'}>{s.specId||'总库存'}：{s.before} → {s.after}</p>)}<button className="shop-button primary" disabled={busy} onClick={async()=>{setBusy(true);try{await updateShopStock(listing.id,stocks);setConfirm(false);await refresh()}catch(cause){setError(message(cause))}finally{setBusy(false)}}}><CheckCircle2 size={16}/>确认修改</button></div>}{error&&<p className="shop-local-error" role="alert">{error}</p>}</div><footer><button className="shop-button" onClick={close}>关闭</button>{canManage&&<button className="shop-button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>刷新详情</button>}{canPublish&&<button className="shop-button primary" disabled={busy||!stocks.some(s=>s.before!==s.after)||stocks.some(s=>!Number.isInteger(s.after)||s.after<0)} onClick={()=>setConfirm(c=>!c)}><Package size={16}/>库存变更预览</button>}{canManage&&canPublish&&<DeleteListing listing={listing} disabled={busy} onBusy={setBusy} deleted={()=>{setListing(current=>({...current,deletion_state:'deleted',status:'deleted'}));setConfirm(false);saved()}}/>}</footer></Modal>
}
