import { useEffect, useState } from 'react'
import { AlertCircle, Bot, ImagePlus, LoaderCircle, RefreshCw, X } from 'lucide-react'
import { cancelAgentJob, getAgentJob, getAgentSettings, runPublishingAgent, type AgentJob, type PublishDraft } from './1688Api'
import ImageStudio from './1688ImageStudio'

export default function AgentPanel({draft,disabled,onBusy,updated}:{draft:PublishDraft;disabled:boolean;onBusy:(busy:boolean)=>void;updated:()=>Promise<void>}){
  const [enabled,setEnabled]=useState(false),[job,setJob]=useState<AgentJob|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[warning,setWarning]=useState('')
  const [studio,setStudio]=useState(false)
  async function load(){try{const [settings,result]=await Promise.all([getAgentSettings(),getAgentJob(draft.id)]);setEnabled(Boolean(settings.data.find(s=>s.id===draft.connection_id)?.enabled));setJob(result.data);if(result.data&&['blocked','failed','unknown'].includes(result.data.status))setWarning(result.data.message||'任务未完成，请核对草稿。')}catch(error){setError(error instanceof Error?error.message:'任务读取失败。')}}
  useEffect(()=>{void load()},[draft.id])
  async function run(){setBusy(true);onBusy(true);setError('');try{const result=await runPublishingAgent(draft.id,draft.revision);setJob(result.data);await updated();if(result.data.status!=='published')setWarning(result.data.message||'自动发布已中止。')}catch(error){setError(error instanceof Error?error.message:'Agent 任务失败。')}finally{setBusy(false);onBusy(false)}}
  const names:Record<string,string>={analyzing:'检测中',publishing:'提交中',published:'已提交平台',blocked:'已中止',failed:'失败',unknown:'待核对',cancelled:'已取消'}
return <section className="shop-comparison" aria-label="Agent 上品任务"><div className="shop-sku-heading"><h3><Bot size={18}/>Agent 上品 · qwen3.8-flash</h3><button className="shop-icon" title="刷新任务" aria-label="刷新 Agent 任务" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/></button></div><div className="shop-inline"><span className="shop-status">{enabled?'模式已开启':'模式已关闭'}</span>{job&&<span className="shop-status">{names[job.status]||job.status}</span>}<button className="shop-button primary" disabled={disabled||busy||!enabled||Boolean(job&&['analyzing','publishing','unknown'].includes(job.status))||!['draft','failed'].includes(draft.status)} onClick={()=>void run()}>{busy?<LoaderCircle className="spin" size={16}/>:<Bot size={16}/>}自动检测并发布</button>{job&&['analyzing','publishing'].includes(job.status)&&!busy&&<button className="shop-button" disabled={disabled} onClick={async()=>{try{await cancelAgentJob(job.id);await load()}catch(error){setError(error instanceof Error?error.message:'取消失败。')}}}><X size={16}/>取消未提交任务</button>}<button className="shop-button" disabled={disabled||busy||!['draft','failed'].includes(draft.status)} onClick={()=>setStudio(true)}><ImagePlus size={16}/>AI 图片工作台</button></div>{job?.report.title&&<p>{job.report.title}</p>}{job?.message&&<p className="shop-note">{job.message}</p>}{error&&<p role="alert" className="shop-local-error">{error}</p>}{job?.report.images&&<details><summary>图片检测结果 · {job.report.images.length} 张</summary>{job.report.images.map((image,index)=><p key={image.url}>图片 {index+1}：{image.reason}</p>)}</details>}
    {warning&&<div className="dialog-layer shop-dialog"><button className="drawer-scrim" aria-label="关闭风险提示" onClick={()=>setWarning('')}/><section className="shop-modal" role="alertdialog" aria-modal="true" aria-label="Agent 上品提示"><header><h2><AlertCircle size={18}/>Agent 上品提示</h2><button title="关闭提示" onClick={()=>setWarning('')}><X size={18}/></button></header><div className="shop-modal-body"><p>{warning}</p></div><footer><button className="shop-button" onClick={()=>setWarning('')}>知道了</button></footer></section></div>}
    {studio&&<ImageStudio draft={draft} close={()=>setStudio(false)} onBusy={onBusy} updated={()=>{void updated()}}/>}
  </section>
}
