import { useState } from 'react'
import { Check, Download, Layers, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { allowsCustom, buildSkuRows, saleDimensions, skuKey, type ReviewedVariant, type SaleChoice, type SaleDimension, type SkuRow } from '../shared/1688-skus'
import { getDraftVariants, mapDraftVariants, refreshSkuRules, type PublishDraft } from './1688Api'

type FormValues=Record<string,any>
export default function SkuEditor({draft,values,disabled,unsaved,change,adopt,onBusy}:{draft:PublishDraft;values:FormValues;disabled:boolean;unsaved:boolean;change:(next:FormValues)=>void;adopt:(result:{data:PublishDraft;missing:string[]})=>void;onBusy:(busy:boolean)=>void}) {
  const dimensions=saleDimensions(draft.platform_schema)
  const extraColumns=(draft.platform_schema.data?.skuTable?.fields?.column||[]).filter((column:any)=>column.visible!==false&&typeof column.name==='string'&&!['sku_props','sku_price','sku_amountOnSale','sku_cargoNumber','sku_status','sku_specId','sku_skuId','sku_picture_url'].includes(column.name)) as Array<{name:string;label:string;uiType:string;readonly?:boolean;precision?:number}>
  const rows:SkuRow[]=Array.isArray(values.skuTable)?values.skuTable:[]
  const [proposal,setProposal]=useState<SkuRow[]|null>(null),[error,setError]=useState(''),[working,setWorking]=useState(false),[mappingOpen,setMappingOpen]=useState(false),[variants,setVariants]=useState<ReviewedVariant[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false)
  const attributes=[...new Set(variants.flatMap(v=>Object.keys(v.attributes)))]
  const cascade=draft.platform_schema.data?.skuTable?.supportLevelProp===true||draft.platform_schema.data?.skuTable?.fields?.supportLevelProp===true
  const update=(next:FormValues)=>{setProposal(null);setConfirmed(false);change(next)}
  async function run(action:()=>Promise<void>){setWorking(true);onBusy(true);setError('');try{await action()}catch(cause){setError(cause instanceof Error?cause.message:'SKU 操作失败。')}finally{setWorking(false);onBusy(false)}}
  const locked=disabled||working||draft.platform_schema.data?.skuTable?.fields?.readonly===true
  const updateRow=(index:number,key:string,value:unknown)=>update({skuTable:rows.map((row,i)=>i===index?{...row,[key]:value}:row)})
  const oldKeys=new Set(rows.map(row=>skuKey(row.sku_props||[])))
  const nextKeys=new Set(proposal?.map(row=>skuKey(row.sku_props))||[])
  return <section className="shop-sku-section" aria-label="销售规格与 SKU">
    <div className="shop-sku-heading"><h3>销售规格与 SKU</h3><div className="shop-row-actions"><button title="映射正式产品规格" aria-label="映射正式产品规格" disabled={locked||unsaved||!dimensions.length} onClick={()=>void run(async()=>{setVariants((await getDraftVariants(draft.id)).data);setMappingOpen(true);setConfirmed(false)})}><Download size={17}/></button>{cascade&&<button title="读取官方 SKU 子规则" aria-label="读取官方 SKU 子规则" disabled={locked||unsaved} onClick={()=>void run(async()=>adopt(await refreshSkuRules(draft.id,draft.revision)))}><RefreshCw size={17}/></button>}</div></div>
    {dimensions.map(d=><SaleDimensionInput key={d.name} dimension={d} selected={Array.isArray(values.saleProp?.[d.name])?values.saleProp[d.name]:[]} disabled={locked} change={selected=>update({saleProp:{...values.saleProp,[d.name]:selected}})}/>)}
    {dimensions.length>0&&!disabled&&<button className="shop-button" disabled={locked} onClick={()=>{setError('');try{setProposal(buildSkuRows(dimensions,values.saleProp||{},rows))}catch(cause){setError(cause instanceof Error?cause.message:'规格组合不合法')}}}><Layers size={16}/>生成组合预览</button>}
    {proposal&&<div className="shop-sku-proposal" role="status"><span>{proposal.length} 个组合 · 保留 {proposal.filter(row=>oldKeys.has(skuKey(row.sku_props))).length} · 新增 {proposal.filter(row=>!oldKeys.has(skuKey(row.sku_props))).length} · 移除 {rows.filter(row=>!nextKeys.has(skuKey(row.sku_props))).length}</span><button className="shop-button" disabled={locked} onClick={()=>update({skuTable:proposal})}><Check size={16}/>应用组合</button></div>}
    {mappingOpen&&<fieldset className="shop-sku-mapping"><legend>正式规格映射 · {variants.length} 个 SKU</legend>{dimensions.map(d=><label key={d.name}>{d.label}{d.required?' *':''}<select aria-label={`平台${d.label}映射`} disabled={locked} value={mapping[d.name]||''} onChange={e=>{setMapping(current=>{const next={...current};if(e.target.value)next[d.name]=e.target.value;else delete next[d.name];return next});setConfirmed(false)}}><option value="">不映射</option>{attributes.map(name=><option key={name}>{name}</option>)}</select></label>)}{!variants.length&&<p className="shop-note">正式产品尚无独立 SKU。</p>}<label className="shop-review-check"><input type="checkbox" checked={confirmed} disabled={locked} onChange={e=>setConfirmed(e.target.checked)}/>确认覆盖草稿销售规格与 SKU，保留正式产品的价格和库存</label><div className="shop-inline"><button className="shop-button" onClick={()=>setMappingOpen(false)}>取消</button><button className="shop-button primary" disabled={locked||unsaved||!confirmed||!variants.length||!Object.keys(mapping).length} onClick={()=>void run(async()=>{adopt(await mapDraftVariants(draft.id,draft.revision,mapping));setMappingOpen(false);setProposal(null)})}><Check size={16}/>确认映射</button></div></fieldset>}
    {rows.length>0&&<div className="shop-table-scroll shop-sku-table"><table className="shop-table"><thead><tr><th>规格</th><th>单价 · 人民币</th><th>可售库存</th><th>单品货号</th><th>上架</th>{extraColumns.map(column=><th key={column.name}>{column.label}</th>)}<th/></tr></thead><tbody>{rows.map((row,index)=><tr key={skuKey(row.sku_props||[])||index}><td>{row.sku_props?.map(p=>p.text).join(' / ')||'规格缺失'}</td><td><input aria-label={`SKU 单价 ${index+1}`} type="number" min="0.01" step="0.01" disabled={locked} value={row.sku_price??''} onChange={e=>updateRow(index,'sku_price',e.target.value===''?null:Number(e.target.value))}/></td><td><input aria-label={`SKU 库存 ${index+1}`} type="number" min="0" step="1" placeholder="待核对" disabled={locked} value={row.sku_amountOnSale??''} onChange={e=>updateRow(index,'sku_amountOnSale',e.target.value===''?null:Number(e.target.value))}/></td><td><input aria-label={`SKU 货号 ${index+1}`} maxLength={80} disabled={locked} value={String(row.sku_cargoNumber||'')} onChange={e=>updateRow(index,'sku_cargoNumber',e.target.value)}/></td><td><input aria-label={`SKU 上架 ${index+1}`} type="checkbox" disabled={locked} checked={row.sku_status!==0} onChange={e=>updateRow(index,'sku_status',e.target.checked?1:0)}/></td>{extraColumns.map(column=><td key={column.name}>{column.readonly||!['cbunumber','cbuinput'].includes(column.uiType)?<span>{String(row[column.name]??'—')}</span>:<input aria-label={`${column.label} ${index+1}`} disabled={locked} type={column.uiType==='cbunumber'?'number':'text'} min={column.uiType==='cbunumber'?0:undefined} step={column.precision?10**-column.precision:1} value={String(row[column.name]??'')} onChange={e=>updateRow(index,column.name,column.uiType==='cbunumber'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}</td>)}<td><button className="shop-icon" title={`移除 SKU ${index+1}`} disabled={locked} onClick={()=>update({skuTable:rows.filter((_,i)=>i!==index)})}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>}
    {error&&<p className="shop-local-error" role="alert">{error}</p>}
  </section>
}

function SaleDimensionInput({dimension,selected,disabled,change}:{dimension:SaleDimension;selected:SaleChoice[];disabled:boolean;change:(selected:SaleChoice[])=>void}) {
  const [text,setText]=useState('')
  const options=(dimension.dataSource||[]).filter(option=>!selected.some(c=>String(c.value)===String(option.value)&&c.text===option.text))
  const canCustom=allowsCustom(dimension)
  const full=Boolean(dimension.maxItems&&selected.length>=dimension.maxItems)
  const add=(choice:SaleChoice)=>{if(!full&&!selected.some(c=>c.text===choice.text&&String(c.value)===String(choice.value)))change([...selected,choice]);setText('')}
  return <fieldset className="shop-sale-dimension"><legend>{dimension.label}{dimension.required?' *':''}</legend><div className="shop-inline">{options.length>0&&<select aria-label={`${dimension.label}枚举规格`} disabled={disabled||full} value="" onChange={e=>{const option=options.find(o=>String(o.value)===e.target.value);if(option)add(option)}}><option value="">选择规格</option>{options.map(o=><option key={`${o.value}-${o.text}`} value={String(o.value)}>{o.text}</option>)}</select>}{canCustom&&<><input aria-label={`${dimension.label}自定义规格`} value={text} maxLength={100} disabled={disabled||full} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();if(text.trim())add({value:-1,text:text.trim(),custom:true})}}}/><button className="shop-icon" title={`添加${dimension.label}`} aria-label={`添加${dimension.label}`} disabled={disabled||full||!text.trim()} onClick={()=>add({value:-1,text:text.trim(),custom:true})}><Plus size={16}/></button></>}</div><div className="shop-spec-values">{selected.map((choice,index)=><span key={`${choice.value}-${choice.text}`}>{choice.text}<button title={`移除 ${choice.text}`} aria-label={`移除 ${choice.text}`} disabled={disabled} onClick={()=>change(selected.filter((_,i)=>i!==index))}><XIcon/></button></span>)}</div></fieldset>
}
function XIcon(){return <Trash2 size={13}/>}
