import {useCallback,useEffect,useRef,useState} from 'react'
import {AlertCircle,Bot,ChevronLeft,ChevronRight,LoaderCircle,RefreshCw,Search,X} from 'lucide-react'
import {getAgentQueue,retryAgentQueueJob,setAgentQueueSetting,type AgentQueueJob,type AgentQueueSetting} from './1688Api'
import type {SessionUser} from './api'
import './1688.css'
const names:Record<AgentQueueJob['status'],string>={queued:'排队中',processing:'处理中',blocked:'需核对',failed:'处理失败',published:'已提交平台',unknown:'结果待核对',cancelled:'已取消'}
export default function AgentQueueSettings({user}:{user:SessionUser}){
 const [shops,setShops]=useState<AgentQueueSetting[]>([]),[jobs,setJobs]=useState<AgentQueueJob[]>([])
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<AgentQueueSetting|null>(null),[confirmed,setConfirmed]=useState(false)
 const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[total,setTotal]=useState(0),[status,setStatus]=useState(''),[shopId,setShopId]=useState(''),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[detail,setDetail]=useState<AgentQueueJob|null>(null)
 const sequence=useRef(0)
 const has=(p:string)=>(user.permissions||[]).some(v=>v==='*'||v===p||v===`${p.split(':')[0]}:*`)
 const editable=has('integration:publish')&&has('integration:manage'),canRead=has('integration:read'),canRetry=has('integration:publish')&&has('collection:read')
 const load=useCallback(async()=>{const ticket=++sequence.current;setLoading(true);setError('');if(!canRead){setLoading(false);return}try{const {data}=await getAgentQueue({page,pageSize,status,connectionId:shopId,search:query});if(ticket!==sequence.current)return;setShops(data.settings);setJobs(data.jobs);setTotal(data.total);if(data.page!==page)setPage(data.page)}catch(cause){if(ticket===sequence.current)setError(cause instanceof Error?cause.message:'队列读取失败。')}finally{if(ticket===sequence.current)setLoading(false)}},[page,pageSize,status,shopId,query,canRead])
 useEffect(()=>{void load();return()=>{sequence.current++}},[load])
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){setDetail(null);setPending(null)}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[busy])
 async function save(shop:AgentQueueSetting,enabled:boolean){setBusy(true);setError('');try{await setAgentQueueSetting(shop.id,enabled,shop.revision);setPending(null);setConfirmed(false);await load()}catch(cause){setError(cause instanceof Error?cause.message:'队列设置保存失败。')}finally{setBusy(false)}}
 async function retry(job:AgentQueueJob){setBusy(true);setError('');try{await retryAgentQueueJob(job.id);setDetail(null);await load()}catch(cause){setError(cause instanceof Error?cause.message:'重新入队失败。')}finally{setBusy(false)}}
 const pages=Math.max(1,Math.ceil(total/pageSize))
 if(!canRead)return <div className="shop-page"><p role="alert">当前账号没有查看上架队列的权限。</p></div>
 return <div className="shop-page queue-page">
  <div className="shop-page-heading"><div><h2>上架队列</h2><p>查看处理进度与异常原因，核对后再继续上架。</p></div><button className="shop-button" disabled={busy||loading} onClick={()=>void load()}><RefreshCw size={16}/>刷新队列</button></div>
  <details className="queue-config"><summary>自动上架设置 <span>{shops.some(s=>s.enabled)?'已开启':'未开启'}</span></summary><p className="shop-note">先在系统设置开启店铺 Agent 模式，再选择自动上架目标店铺。</p>{shops.map(shop=><div className="queue-shop" key={shop.id}><span title={shop.display_name}>{shop.display_name}</span><small>Agent {shop.agent_enabled?'已开启':'未开启'}</small><label className="agent-switch"><input type="checkbox" role="switch" aria-label={`${shop.display_name} 采集后自动上品`} checked={shop.enabled} disabled={!editable||busy||loading||(!shop.enabled&&(!shop.agent_enabled||shop.connection_status!=='connected'))} onChange={e=>{if(e.target.checked){setPending(shop);setConfirmed(false)}else void save(shop,false)}}/>{shop.enabled?'自动上架已开启':'自动上架关闭'}</label></div>)}{!shops.length&&!loading&&<p>暂无已授权店铺。</p>}</details>
  <form className="queue-filters" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search.trim())}}><label className="queue-search"><Search size={17}/><input aria-label="搜索队列商品" placeholder="搜索商品标题" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="任务状态" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">全部状态</option>{Object.entries(names).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="目标店铺" value={shopId} onChange={e=>{setShopId(e.target.value);setPage(1)}}><option value="">全部店铺</option>{shops.map(shop=><option key={shop.id} value={shop.id}>{shop.display_name}</option>)}</select><button className="shop-button" type="submit">搜索</button></form>
  {error&&<p className="shop-local-error" role="alert"><AlertCircle size={16}/>{error}<button className="shop-button" disabled={loading} onClick={()=>void load()}>重试加载</button></p>}
  <section className="queue-card" aria-label="上架任务列表" aria-busy={loading}>
   <div className="queue-table-wrap"><table className="queue-table"><colgroup><col style={{width:'27%'}}/><col style={{width:'16%'}}/><col style={{width:'13%'}}/><col style={{width:'25%'}}/><col style={{width:'12%'}}/><col style={{width:'7%'}}/></colgroup><thead><tr><th>商品</th><th>店铺</th><th>状态</th><th>最近结果</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{!loading&&!error&&jobs.map(job=><tr key={job.id}><td><button className="queue-title queue-clamp" title={job.title} onClick={()=>setDetail(job)}>{job.title}</button></td><td><span className="queue-clamp" title={job.display_name}>{job.display_name}</span></td><td><span className={`queue-state queue-state-${job.status}`}>{names[job.status]}</span></td><td><span className="queue-clamp queue-result">{job.message||'等待下一步处理'}</span></td><td><time className="queue-time">{new Date(job.updated_at).toLocaleDateString('zh-CN')}<br/>{new Date(job.updated_at).toLocaleTimeString('zh-CN',{hour12:false})}</time></td><td><button className="queue-detail-button" aria-label={`查看任务 ${job.title}`} onClick={()=>setDetail(job)}>详情</button></td></tr>)}</tbody></table></div>
   {loading?<div className="shop-empty" role="status"><LoaderCircle className="spin"/>正在加载任务…</div>:error?<div className="shop-empty">队列加载失败，请重试。</div>:!jobs.length&&<div className="shop-empty">{query||status||shopId?'没有符合筛选条件的任务。':'暂无上架任务。开启自动上架后，新采集的商品将在这里显示。'}</div>}
   <div className="queue-pagination"><span>共 {total} 条</span><label>每页 <select aria-label="每页条数" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[10,20,50].map(n=><option key={n} value={n}>{n} 条</option>)}</select></label><div><button className="shop-icon" aria-label="上一页" disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>第 {page} / {pages} 页</span><button className="shop-icon" aria-label="下一页" disabled={loading||page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div>
  </section>
  {detail&&<div className="dialog-layer shop-dialog"><button className="drawer-scrim" aria-label="关闭任务详情" onClick={()=>setDetail(null)}/><section className="shop-modal queue-modal" role="dialog" aria-modal="true" aria-label="上架任务详情"><header><h2>上架任务详情</h2><button aria-label="关闭详情" onClick={()=>setDetail(null)}><X size={18}/></button></header><div className="shop-modal-body"><h3>{detail.title}</h3><p>{detail.display_name}</p><p><span className={`queue-state queue-state-${detail.status}`}>{names[detail.status]}</span> · 已尝试 {detail.attempts} 次</p><h3>最近处理结果</h3><p className="queue-full-message">{detail.message||'暂无处理结果。'}</p>{detail.draft_id&&<p className="shop-note">已生成发布草稿，请到“1688 店铺 → 发布工作台”核对处理，避免重复上品。</p>}</div><footer><button className="shop-button" onClick={()=>setDetail(null)}>关闭</button>{canRetry&&['blocked','failed'].includes(detail.status)&&!detail.product_id&&!detail.draft_id&&<button className="shop-button primary" disabled={busy} onClick={()=>void retry(detail)}>重新入队</button>}</footer></section></div>}
    {pending&&<div className="dialog-layer shop-dialog"><button className="drawer-scrim" aria-label="取消开启队列" disabled={busy} onClick={()=>setPending(null)}/><section className="shop-modal" role="dialog" aria-modal="true" aria-label="开启采集自动上品"><header><h2>开启采集自动上品</h2><button title="关闭" disabled={busy} onClick={()=>setPending(null)}><X size={18}/></button></header><div className="shop-modal-body"><p>目标店铺：{pending.display_name}</p><p>新采集的 1688 商品将排队筛查，资料齐全时自动提交平台。价格、库存、类目或图片存在不确定性时中止；平台审核结果需另行核对。</p><label className="shop-review-check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={event=>setConfirmed(event.target.checked)}/>确认商品及全部图片使用权，并授权该店铺自动提交</label></div><footer><button className="shop-button" disabled={busy} onClick={()=>setPending(null)}>取消</button><button className="shop-button primary" disabled={busy||!confirmed} onClick={()=>void save(pending,true)}><Bot size={16}/>开启队列</button></footer></section></div>} </div>
}
