import { useState } from 'react'
import { CheckCircle2, LoaderCircle, X } from 'lucide-react'
import { promoteCollectedProduct, type CollectedProductDetail } from './api'
import './1688.css'

export default function CollectionPromotion({detail,close,saved}:{detail:CollectedProductDetail;close:()=>void;saved:()=>void}) {
  const source=detail.product
  const [sku,setSku]=useState(`1688-${source.source_product_id}`),[name,setName]=useState(source.title),[category,setCategory]=useState(source.category_path||'')
  const [price,setPrice]=useState(source.price_min||''),[description,setDescription]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [variants,setVariants]=useState(detail.variants.map(v=>({...v,reviewPrice:v.price||'',reviewStock:v.stock||''})))
  return <div className="dialog-layer shop-dialog"><button className="drawer-scrim" onClick={close} aria-label="关闭审核"/><section className="shop-modal wide" role="dialog" aria-modal="true" aria-label="审核并创建正式产品"><header><h2>审核并创建正式产品</h2><button onClick={close} aria-label="关闭"><X size={18}/></button></header><form onSubmit={async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{await promoteCollectedProduct(source.id,{sku,name,category:category||null,basePrice:Number(price),description,specifications:source.attributes,reviewed:true,variants:variants.map(v=>({id:v.id,price:Number(v.reviewPrice),stock:v.reviewStock===''?null:Number(v.reviewStock)}))});saved()}catch(cause){setError(cause instanceof Error?cause.message:'创建正式产品失败。')}finally{setBusy(false)}}}><div className="shop-modal-body"><div className="shop-form-columns"><label>产品货号<input required value={sku} maxLength={80} onChange={e=>setSku(e.target.value)}/></label><label>分类<input value={category} maxLength={120} onChange={e=>setCategory(e.target.value)}/></label></div><label>正式产品名称<input required value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><label>基础单价 · 人民币<input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>产品描述<textarea value={description} rows={4} maxLength={10000} onChange={e=>setDescription(e.target.value)}/></label><dl>{Object.entries(source.attributes).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>{variants.length>0&&<div className="shop-table-scroll"><table className="shop-table"><thead><tr><th>规格</th><th>人民币单价</th><th>库存</th></tr></thead><tbody>{variants.map((v,index)=><tr key={v.id}><td>{v.label}</td><td><input aria-label={`规格单价 ${index+1}`} required type="number" min="0" step="0.01" value={v.reviewPrice} onChange={e=>setVariants(current=>current.map((item,i)=>i===index?{...item,reviewPrice:e.target.value}:item))}/></td><td><input aria-label={`规格库存 ${index+1}`} type="number" min="0" step="1" placeholder="未知" value={v.reviewStock} onChange={e=>setVariants(current=>current.map((item,i)=>i===index?{...item,reviewStock:e.target.value}:item))}/></td></tr>)}</tbody></table></div>}<label className="shop-review-check"><input type="checkbox" required checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>已核对名称、人民币价格、规格、库存及图片使用权</label>{source.currency!=='CNY'&&<p className="shop-local-error">来源价格不是人民币，不能直接转为正式产品。</p>}{error&&<p className="shop-local-error" role="alert">{error}</p>}</div><footer><button type="button" className="shop-button" onClick={close}>取消</button><button className="shop-button primary" disabled={busy||!reviewed||source.currency!=='CNY'}>{busy?<LoaderCircle size={16} className="spin"/>:<CheckCircle2 size={16}/>}创建正式产品</button></footer></form></section></div>
}
