import { useCallback, useEffect, useMemo, useState, type DragEvent, type FormEvent } from 'react'
import { AlertCircle, ArrowRight, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, GripVertical, Inbox, ListChecks, LoaderCircle, Pencil, Plus, RefreshCw, Search, Target, Trash2, TrendingUp, UserRound, X } from 'lucide-react'
import { advanceOpportunity, ApiError, createOpportunity, createOpportunityActivity, deleteOpportunity, getAccount, getAccounts, getAssignableUsers, getOpportunity, getOpportunities, updateOpportunity, type Account, type AssignableUser, type Contact, type Opportunity, type OpportunityBoard, type OpportunityDetail, type OpportunityInput, type OpportunityStage } from './api'

const money = (value:string|number|undefined) => new Intl.NumberFormat('zh-CN',{ style:'currency',currency:'CNY',maximumFractionDigits:0 }).format(Number(value??0))
const opportunityBreakdown = (items:Opportunity[]) => money(items.reduce((sum,item)=>sum+Number(item.amount),0))
const shortDate = (value:string|null) => value ? new Intl.DateTimeFormat('zh-CN',{ month:'short',day:'numeric' }).format(new Date(value)) : '未设置'
const emptyInput:OpportunityInput = { accountId:'',stageId:'',name:'',description:'',amount:0,expectedCloseDate:null,probability:null }

export default function OpportunitiesPage() {
  const [board,setBoard] = useState<OpportunityBoard|null>(null)
  const [search,setSearch] = useState('')
  const [appliedSearch,setAppliedSearch] = useState('')
  const [loading,setLoading] = useState(true)
  const [error,setError] = useState('')
  const [notice,setNotice] = useState('')
  const [creating,setCreating] = useState(false)
  const [selected,setSelected] = useState<Opportunity|null>(null)
  const [moving,setMoving] = useState<{ opportunity:Opportunity;stage:OpportunityStage }|null>(null)
  const [deleting,setDeleting] = useState<Opportunity|null>(null)
  const load = useCallback(async () => { setLoading(true);setError('');try { setBoard(await getOpportunities({ search:appliedSearch })) } catch(cause) { setError(cause instanceof ApiError?cause.message:'无法加载商机管道。') } finally { setLoading(false) } },[appliedSearch])
  useEffect(() => { void load() },[load])
  const openStages = board?.stages.filter(stage => !stage.is_won && !stage.is_lost) ?? []
  const closedStages = board?.stages.filter(stage => stage.is_won || stage.is_lost) ?? []
  async function remove(opportunity:Opportunity) { try { await deleteOpportunity(opportunity.id);setNotice('商机已删除');await load() } catch(cause) { setError(cause instanceof Error?cause.message:'删除商机失败。') } finally { setDeleting(null) } }
  function drop(event:DragEvent,stage:OpportunityStage) { event.preventDefault();const id=event.dataTransfer.getData('text/opportunity-id');const opportunity=board?.data.find(item=>item.id===id);if(opportunity&&opportunity.stage_id!==stage.id)setMoving({ opportunity,stage }) }

  return <div className="opportunity-page">
    {notice&&<div className="inline-notice">{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}
    <section className="opportunity-toolbar"><div className="view-title"><p className="kicker">LIVE PIPELINE</p><h2>销售管道</h2></div><div className="toolbar-actions"><form className="lead-search" onSubmit={event=>{event.preventDefault();setAppliedSearch(search.trim())}}><Search size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="商机或客户名称"/><button>搜索</button></form><button className="primary" onClick={()=>setCreating(true)}><Plus size={16}/> 新建商机</button></div></section>
    {error&&<section className="state-card error-state"><AlertCircle size={25}/><h2>商机管道暂时无法加载</h2><p>{error}</p><button onClick={()=>void load()}><RefreshCw size={15}/>重新加载</button></section>}
    {!error&&loading&&<section className="state-card"><LoaderCircle className="spin" size={27}/><p>正在计算销售管道…</p></section>}
    {!error&&!loading&&board&&<>
      <PipelineForecast board={board}/>
      {!board.data.length?<section className="state-card"><Inbox size={28}/><h2>{appliedSearch?'没有匹配的商机':'从第一个成交目标开始'}</h2><p>{appliedSearch?'调整搜索词后再试。':'为客户建立商机，它会出现在销售管道中。'}</p><button onClick={()=>setCreating(true)}><Plus size={15}/>新建商机</button></section>:<section className="pipeline-board" aria-label="商机销售看板">{openStages.map(stage=><PipelineColumn key={stage.id} stage={stage} opportunities={board.data.filter(item=>item.stage_id===stage.id)} onOpen={setSelected} onDelete={setDeleting} onDrop={event=>drop(event,stage)}/>)}<div className="closed-lane">{closedStages.map(stage=><PipelineColumn key={stage.id} stage={stage} opportunities={board.data.filter(item=>item.stage_id===stage.id)} onOpen={setSelected} onDelete={setDeleting} onDrop={event=>drop(event,stage)} compact/>)}</div></section>}
    </>}
    {(creating||selected)&&<OpportunityDrawer opportunity={selected} stages={board?.stages??[]} onClose={()=>{setCreating(false);setSelected(null)}} onSaved={async message=>{setCreating(false);setSelected(null);setNotice(message);await load()}}/>}
    {moving&&<AdvanceDialog moving={moving} onClose={()=>setMoving(null)} onAdvanced={async()=>{setMoving(null);setNotice(`已推进至${moving.stage.name}`);await load()}}/>}
    {deleting&&<div className="dialog-layer"><button className="drawer-scrim" onClick={()=>setDeleting(null)}/><section className="confirm-dialog"><div className="confirm-icon"><Trash2 size={20}/></div><h2>删除这条商机？</h2><p>“{deleting.name}”将从销售管道中移除，阶段历史和审计记录仍会保留。</p><div><button onClick={()=>setDeleting(null)}>取消</button><button className="danger" onClick={()=>void remove(deleting)}>删除商机</button></div></section></div>}
  </div>
}

function PipelineForecast({ board }:{ board:OpportunityBoard }) {
  const max=Math.max(...board.stages.map(stage=>stage.opportunity_count??0),1)
  return <section className="pipeline-forecast"><div className="forecast-copy"><span>加权预测</span><strong>{money(board.summary.weightedAmount)}</strong><small>管道总额 {money(board.summary.totalAmount)} · {board.summary.closingThisMonth} 笔预计本月关闭</small></div><div className="forecast-rail">{board.stages.filter(stage=>!stage.is_lost).map(stage=><article key={stage.id} style={{ '--stage-fill':`${Math.max(8,(stage.opportunity_count??0)/max*100)}%` } as React.CSSProperties}><div><span>{stage.name}</span><b>{stage.opportunity_count??0}</b></div><i/><small>{money(stage.weighted_amount)} 加权</small></article>)}</div></section>
}

function PipelineColumn({ stage,opportunities,onOpen,onDelete,onDrop,compact=false }:{ stage:OpportunityStage;opportunities:Opportunity[];onOpen:(item:Opportunity)=>void;onDelete:(item:Opportunity)=>void;onDrop:(event:DragEvent)=>void;compact?:boolean }) {
  return <section className={`pipeline-column ${compact?'compact':''} ${stage.is_won?'won-column':''} ${stage.is_lost?'lost-column':''}`} onDragOver={event=>event.preventDefault()} onDrop={onDrop}><header><div><span>{stage.position.toString().padStart(2,'0')} / {stage.default_probability}%</span><h3>{stage.name}</h3></div><b>{opportunities.length}</b><small>{opportunityBreakdown(opportunities)}</small></header><div className="opportunity-stack">{opportunities.map(item=><article key={item.id} draggable onDragStart={event=>{event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/opportunity-id',item.id)}}><button className="card-main" onClick={()=>onOpen(item)}><div className="card-grip"><GripVertical size={14}/><span>{item.account_name}</span></div><h4>{item.name}</h4><strong>{money(item.amount)}</strong><div className="deal-meta"><span><CalendarDays size={12}/>{shortDate(item.expected_close_date)}</span><span><UserRound size={12}/>{item.owner_name||'待分配'}</span></div><div className="probability-line"><i style={{ width:`${Number(item.probability??item.default_probability)}%` }}/><small>{Number(item.probability??item.default_probability)}%</small></div></button><div className="card-actions"><button onClick={()=>onOpen(item)} aria-label={`编辑 ${item.name}`}><Pencil size={13}/></button><button onClick={()=>onDelete(item)} aria-label={`删除 ${item.name}`}><Trash2 size={13}/></button><button onClick={()=>onOpen(item)} aria-label={`查看 ${item.name}`}><ChevronRight size={14}/></button></div></article>)}</div>{!opportunities.length&&<div className="column-empty">拖动商机到这里</div>}</section>
}

function OpportunityDrawer({ opportunity,stages,onClose,onSaved }:{ opportunity:Opportunity|null;stages:OpportunityStage[];onClose:()=>void;onSaved:(message:string)=>Promise<void> }) {
  const [view,setView]=useState<'overview'|'advance'|'followup'|'history'>('overview')
  const [detail,setDetail]=useState<OpportunityDetail|null>(null)
  const [accounts,setAccounts]=useState<Account[]>([])
  const [contacts,setContacts]=useState<Contact[]>([])
  const [users,setUsers]=useState<AssignableUser[]>([])
  const [form,setForm]=useState<OpportunityInput>(()=>opportunity?{accountId:opportunity.account_id,primaryContactId:opportunity.primary_contact_id,ownerId:opportunity.owner_id,stageId:opportunity.stage_id,name:opportunity.name,description:opportunity.description,amount:Number(opportunity.amount),expectedCloseDate:opportunity.expected_close_date,probability:Number(opportunity.probability??opportunity.default_probability),lostReason:opportunity.lost_reason}:emptyInput)
  const [loading,setLoading]=useState(Boolean(opportunity));const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const refresh=useCallback(async()=>{if(!opportunity)return;setLoading(true);try{setDetail((await getOpportunity(opportunity.id)).data)}catch(cause){setError(cause instanceof Error?cause.message:'商机详情加载失败。')}finally{setLoading(false)}},[opportunity])
  useEffect(()=>{void Promise.all([getAccounts(),getAssignableUsers()]).then(([accountResult,userResult])=>{setAccounts(accountResult.data);setUsers(userResult.data)});void refresh()},[refresh])
  useEffect(()=>{if(form.accountId)void getAccount(form.accountId).then(result=>setContacts(result.data.contacts));else setContacts([])},[form.accountId])
  useEffect(()=>{if(!opportunity&&!form.stageId&&stages.length){const initial=stages.find(stage=>stage.code==='initial_contact')??stages[0];setForm(current=>({...current,stageId:initial.id,probability:Number(initial.default_probability)}))}},[opportunity,form.stageId,stages])
  const set=(key:keyof OpportunityInput,value:string|number|null)=>setForm(current=>({...current,[key]:value}))
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{if(opportunity)await updateOpportunity(opportunity.id,{name:form.name,description:form.description,amount:Number(form.amount),expectedCloseDate:form.expectedCloseDate,probability:form.probability,ownerId:form.ownerId,lostReason:form.lostReason});else await createOpportunity(form);await onSaved(opportunity?'商机已更新':'商机已创建')}catch(cause){setError(cause instanceof Error?cause.message:'保存商机失败。')}finally{setSaving(false)}}
  return <div className="drawer-layer"><button className="drawer-scrim" onClick={onClose}/><aside className="record-drawer opportunity-drawer"><header><div><p className="kicker">{opportunity?`${opportunity.stage_name} · ${opportunity.account_name}`:'建立成交目标'}</p><h2>{opportunity?.name||'新建商机'}</h2></div><button onClick={onClose}><X size={20}/></button></header>{opportunity&&<nav className="drawer-tabs"><button className={view==='overview'?'active':''} onClick={()=>setView('overview')}>商机资料</button><button className={view==='advance'?'active':''} onClick={()=>setView('advance')}>推进阶段</button><button className={view==='followup'?'active':''} onClick={()=>setView('followup')}>跟进 <span>{detail?.activities.length??0}</span></button><button className={view==='history'?'active':''} onClick={()=>setView('history')}>阶段历史 <span>{detail?.history.length??0}</span></button></nav>}
    {loading?<div className="drawer-loading"><LoaderCircle className="spin" size={25}/><span>正在读取商机轨迹…</span></div>:view==='overview'&&<form onSubmit={submit}><div className="deal-hero"><div><span>预计金额</span><strong>{money(form.amount)}</strong></div><div className="deal-gauge" style={{'--probability':`${form.probability??0}%`} as React.CSSProperties}><b>{form.probability??0}%</b><small>成交概率</small></div></div><div className="form-grid"><label className="full"><span>商机名称 *</span><input value={form.name} onChange={event=>set('name',event.target.value)} required autoFocus={!opportunity}/></label><label className="full"><span>关联客户 *</span><select value={form.accountId} onChange={event=>{set('accountId',event.target.value);set('primaryContactId',null)}} disabled={Boolean(opportunity)} required><option value="">请选择客户</option>{accounts.map(account=><option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label><span>主联系人</span><select value={form.primaryContactId??''} onChange={event=>set('primaryContactId',event.target.value||null)} disabled={Boolean(opportunity)}><option value="">未指定</option>{contacts.map(contact=><option value={contact.id} key={contact.id}>{contact.full_name}</option>)}</select></label><label><span>负责人</span><select value={form.ownerId??''} onChange={event=>set('ownerId',event.target.value||null)}><option value="">当前用户</option>{users.map(user=><option value={user.id} key={user.id}>{user.display_name}</option>)}</select></label>{!opportunity&&<label><span>初始阶段</span><select value={form.stageId} onChange={event=>{const stage=stages.find(item=>item.id===event.target.value);set('stageId',event.target.value);if(stage)set('probability',Number(stage.default_probability))}}>{stages.map(stage=><option value={stage.id} key={stage.id}>{stage.name} · {stage.default_probability}%</option>)}</select></label>}<label><span>预计金额（元）</span><input type="number" min="0" step="0.01" value={form.amount} onChange={event=>set('amount',Number(event.target.value))}/></label><label><span>计价币种</span><input value="人民币 CNY" disabled/></label><label><span>预计成交日期</span><input type="date" value={form.expectedCloseDate??''} onChange={event=>set('expectedCloseDate',event.target.value||null)}/></label><label><span>成交概率</span><input type="number" min="0" max="100" value={form.probability??''} onChange={event=>set('probability',event.target.value?Number(event.target.value):null)}/></label><label className="full"><span>需求描述</span><textarea value={form.description??''} onChange={event=>set('description',event.target.value)} placeholder="产品、数量、交期或关键约束"/></label></div>{error&&<div className="form-error">{error}</div>}<footer><button type="button" onClick={onClose}>取消</button><button className="primary" disabled={saving}>{saving?'正在保存…':opportunity?'保存商机':'创建商机'}</button></footer></form>}
    {!loading&&detail&&view==='advance'&&<AdvanceWorkspace opportunity={opportunity!} stages={stages} onAdvanced={()=>onSaved('商机阶段已推进')}/>} {!loading&&detail&&view==='followup'&&<FollowupWorkspace opportunity={opportunity!} detail={detail} refresh={refresh}/>} {!loading&&detail&&view==='history'&&<HistoryWorkspace detail={detail}/>} 
  </aside></div>
}

function FollowupWorkspace({opportunity,detail,refresh}:{opportunity:Opportunity;detail:OpportunityDetail;refresh:()=>Promise<void>}) {
  const [content,setContent]=useState('');const [type,setType]=useState('note');const [nextAction,setNextAction]=useState('');const [nextActionAt,setNextActionAt]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await createOpportunityActivity(opportunity.id,{activityType:type,content,nextAction:nextAction||null,nextActionAt:nextActionAt?new Date(nextActionAt).toISOString():null});setContent('');setNextAction('');setNextActionAt('');await refresh()}catch(cause){setError(cause instanceof Error?cause.message:'保存跟进失败。')}finally{setSaving(false)}}
  return <div className="activity-workspace"><form className="activity-compose" onSubmit={submit}><div><select value={type} onChange={event=>setType(event.target.value)}><option value="note">备注</option><option value="call">电话</option><option value="wechat">微信</option><option value="email">邮件</option><option value="meeting">拜访 / 会议</option></select><span>记录本次推进</span></div><textarea value={content} onChange={event=>setContent(event.target.value)} placeholder="记录客户反馈、关键异议或已确认事项" required/><div className="next-action-fields"><input value={nextAction} onChange={event=>setNextAction(event.target.value)} placeholder="下一步行动（可选）"/><input type="datetime-local" value={nextActionAt} onChange={event=>setNextActionAt(event.target.value)}/></div>{error&&<div className="form-error">{error}</div>}<button disabled={saving}>{saving?'保存中…':'保存跟进'}</button></form><div className="timeline"><p className="kicker">沟通时间线</p>{!detail.activities.length?<div className="timeline-empty"><ListChecks size={23}/><p>记录第一次沟通，后续行动会自动进入待办。</p></div>:detail.activities.map(item=><article key={item.id}><i/><div><header><b>{item.subject||item.activity_type}</b><span>{shortDate(item.occurred_at)}</span></header><p>{item.content}</p>{item.next_action&&<small>下一步：{item.next_action}</small>}</div></article>)}</div></div>
}

function HistoryWorkspace({detail}:{detail:OpportunityDetail}) {
  return <div className="history-workspace"><div className="current-stage"><Target size={20}/><div><span>当前阶段</span><strong>{detail.opportunity.stage_name}</strong></div><b>{detail.opportunity.probability??detail.opportunity.default_probability}%</b></div><div className="stage-history">{detail.history.map((item,index)=><article key={item.id}><div className="history-marker">{index===0?<CheckCircle2 size={15}/>:<ArrowRight size={14}/>}</div><div><header><b>{item.from_stage_name?`${item.from_stage_name} → ${item.to_stage_name}`:item.to_stage_name}</b><time>{shortDate(item.created_at)}</time></header><p>{item.note||'阶段已更新'}</p><span>{item.changed_by_name||'系统'}</span></div></article>)}</div>{detail.tasks.filter(item=>!['done','cancelled'].includes(item.status)).length>0&&<section className="open-tasks"><p className="kicker">未完成行动</p>{detail.tasks.filter(item=>!['done','cancelled'].includes(item.status)).map(item=><article key={item.id}><Clock3 size={14}/><div><b>{item.title}</b><span>{shortDate(item.due_at)} · {item.assignee_name||'待分配'}</span></div></article>)}</section>}</div>
}

function AdvanceWorkspace({opportunity,stages,onAdvanced}:{opportunity:Opportunity;stages:OpportunityStage[];onAdvanced:()=>Promise<void>}) {
  const candidates=stages.filter(stage=>stage.id!==opportunity.stage_id)
  const suggested=candidates.find(stage=>stage.position===opportunity.stage_position+1)??candidates[0]
  const [stageId,setStageId]=useState(suggested?.id??'');const [note,setNote]=useState('');const [nextAction,setNextAction]=useState('');const [nextActionAt,setNextActionAt]=useState('');const [lostReason,setLostReason]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const target=stages.find(stage=>stage.id===stageId)
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await advanceOpportunity(opportunity.id,{stageId,note,nextAction:nextAction||null,nextActionAt:nextActionAt?new Date(nextActionAt).toISOString():null,lostReason:lostReason||null});await onAdvanced()}catch(cause){setError(cause instanceof Error?cause.message:'推进阶段失败。')}finally{setSaving(false)}}
  return <form className="advance-workspace" onSubmit={submit}><div className="stage-route-card"><span>{opportunity.stage_name}</span><ArrowRight size={18}/><strong>{target?.name??'选择目标阶段'}</strong></div><div className="advance-copy"><p className="kicker">STAGE CHECKPOINT</p><h3>确认本次推进</h3><p>确认后将更新成交概率，并同时写入阶段历史与客户互动时间线。</p></div><div className="form-grid"><label className="full"><span>目标阶段</span><select value={stageId} onChange={event=>setStageId(event.target.value)}>{candidates.map(stage=><option value={stage.id} key={stage.id}>{stage.name} · {stage.default_probability}%</option>)}</select></label><label className="full"><span>推进说明 *</span><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="客户确认了什么？当前还有哪些关键事项？" required/></label>{target?.is_lost&&<label className="full"><span>丢单原因 *</span><input value={lostReason} onChange={event=>setLostReason(event.target.value)} required/></label>}<label><span>下一步行动</span><input value={nextAction} onChange={event=>setNextAction(event.target.value)}/></label><label><span>计划时间</span><input type="datetime-local" value={nextActionAt} onChange={event=>setNextActionAt(event.target.value)}/></label></div>{error&&<div className="form-error">{error}</div>}<footer><button type="button" onClick={()=>{setNote('');setNextAction('');setNextActionAt('')}}>清空</button><button className="primary" disabled={saving||!stageId}>{saving?'正在推进…':'确认推进'}</button></footer></form>
}

function AdvanceDialog({moving,onClose,onAdvanced}:{moving:{opportunity:Opportunity;stage:OpportunityStage};onClose:()=>void;onAdvanced:()=>Promise<void>}) {
  const [note,setNote]=useState('');const [nextAction,setNextAction]=useState('');const [nextActionAt,setNextActionAt]=useState('');const [lostReason,setLostReason]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await advanceOpportunity(moving.opportunity.id,{stageId:moving.stage.id,note,nextAction:nextAction||null,nextActionAt:nextActionAt?new Date(nextActionAt).toISOString():null,lostReason:lostReason||null});await onAdvanced()}catch(cause){setError(cause instanceof Error?cause.message:'推进阶段失败。')}finally{setSaving(false)}}
  return <div className="dialog-layer"><button className="drawer-scrim" onClick={onClose}/><form className="advance-dialog" onSubmit={submit}><div className="advance-route"><span>{moving.opportunity.stage_name}</span><ArrowRight size={17}/><strong>{moving.stage.name}</strong></div><h2>记录这次推进</h2><p>阶段变化会同步更新成交概率并写入客户 360 时间线。</p><label><span>推进说明 *</span><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="例如：客户确认规格，进入正式报价" required autoFocus/></label>{moving.stage.is_lost&&<label><span>丢单原因 *</span><input value={lostReason} onChange={event=>setLostReason(event.target.value)} required/></label>}<div className="advance-next"><label><span>下一步行动</span><input value={nextAction} onChange={event=>setNextAction(event.target.value)}/></label><label><span>计划时间</span><input type="datetime-local" value={nextActionAt} onChange={event=>setNextActionAt(event.target.value)}/></label></div>{error&&<div className="form-error">{error}</div>}<footer><button type="button" onClick={onClose}>取消</button><button className="primary" disabled={saving}>{saving?'正在推进…':'确认推进'}</button></footer></form></div>
}
