import { useCallback,useEffect,useState } from 'react'
import { AlertCircle,Bot,Box,ChevronRight,Copy,Database,ExternalLink,Inbox,KeyRound,LoaderCircle,RefreshCw,Search,Trash2,X } from 'lucide-react'
import { ApiError,COLLECTOR_SCRIPT_URL,createCollectorKey,deleteCollectedProduct,getCollectedProduct,getCollectedProducts,type CollectedProduct,type CollectedProductDetail,type SessionUser } from './api'
import CollectionPromotion from './CollectionPromotion'
import { enqueueCollectedProduct } from './1688Api'

const money=(value:string|number)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(Number(value))
const queueNames:Record<NonNullable<CollectedProduct['queue_status']>,string>={queued:'排队中',processing:'Agent 处理中',blocked:'需核对',failed:'处理失败',published:'已提交平台',unknown:'结果待核对',cancelled:'已取消'}
const collectionStatus=(item:CollectedProduct)=>item.queue_status?queueNames[item.queue_status]:({collected:'已采集',ai_processing:'处理中',ai_completed:'已清洗',ready:'已审核',published:'已发布',failed:'处理失败'} as const)[item.processing_status]

export default function ProductCollectionsPage({user}:{user:SessionUser}){
 const [promoting,setPromoting]=useState<CollectedProductDetail|null>(null)
 const canCreate=(user.permissions||[]).some(p=>p==='*'||p==='product:*'||p==='product:create')
 const [collections,setCollections]=useState<CollectedProduct[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[collectionDetail,setCollectionDetail]=useState<CollectedProductDetail|null>(null),[collectorSetup,setCollectorSetup]=useState(false),[deletingCollection,setDeletingCollection]=useState<CollectedProduct|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError('');try{setCollections((await getCollectedProducts({search:search||undefined})).data)}catch(cause){setError(cause instanceof ApiError?cause.message:'采集商品数据加载失败。')}finally{setLoading(false)}},[search])
 useEffect(()=>{void load()},[load])
 async function removeCollection(item:CollectedProduct){try{await deleteCollectedProduct(item.id);setNotice('采集记录已删除');await load()}catch(cause){setError(cause instanceof Error?cause.message:'删除采集记录失败。')}finally{setDeletingCollection(null)}}
 async function openCollection(item:CollectedProduct){try{setCollectionDetail((await getCollectedProduct(item.id)).data)}catch(cause){setError(cause instanceof Error?cause.message:'采集详情加载失败。')}}
 async function enqueue(item:CollectedProductDetail){try{await enqueueCollectedProduct(item.product.id);setCollectionDetail(null);setNotice('已加入 Agent 队列');await load()}catch(cause){setError(cause instanceof Error?cause.message:'加入队列失败。')}}
 return <div className="commerce-page collection-page">
  {notice&&<div className="inline-notice">{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}
  <section className="commerce-toolbar"><div className="view-title"><p className="kicker">1688 / Alibaba</p><h2>采集商品工作区</h2></div><div className="toolbar-actions"><div className="lead-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="商品名称或 1688 ID"/></div><button className="primary" onClick={()=>setCollectorSetup(true)}><KeyRound size={16}/>配置采集器</button></div></section>
  {error&&<section className="state-card error-state"><AlertCircle size={25}/><h2>数据暂时无法加载</h2><p>{error}</p><button onClick={()=>void load()}><RefreshCw size={15}/>重新加载</button></section>}
  {!error&&loading&&<section className="state-card"><LoaderCircle className="spin" size={27}/><p>正在同步采集商品数据…</p></section>}
  {!error&&!loading&&!collections.length&&<section className="state-card"><Inbox size={28}/><h2>采集第一件 1688 商品</h2><p>安装商品采集器并配置专用密钥，在商品详情页直接保存完整商品，也可以从列表页批量采集。</p><button onClick={()=>setCollectorSetup(true)}><KeyRound size={15}/>配置采集器</button></section>}
  {!error&&!loading&&collections.length>0&&<section className="collection-grid">{collections.map(item=><article key={item.id}><div className="collection-image">{item.main_image_url?<img src={item.main_image_url} alt="" referrerPolicy="no-referrer"/>:<Database size={25}/>}<span>{item.source}</span></div><div className="collection-copy"><small>货号 {item.source_product_id}</small><h3>{item.title}</h3><div><span>{item.variant_count} 个 SKU</span><span>{item.min_price==null?'价格待确认':item.min_price===item.max_price?money(item.min_price):`${money(item.min_price)} - ${money(item.max_price!)}`}</span></div>{item.queue_message&&<p className="collection-queue-message">{item.queue_message}</p>}<footer><span className="status-pill collection-status">{collectionStatus(item)}</span><time>{new Date(item.collected_at).toLocaleString('zh-CN')}</time><button onClick={()=>void openCollection(item)} aria-label={`查看 ${item.title}`}><ChevronRight size={16}/></button><button onClick={()=>setDeletingCollection(item)} aria-label={`删除 ${item.title}`}><Trash2 size={14}/></button></footer></div></article>)}</section>}
  {collectionDetail&&<><CollectionPreview detail={collectionDetail} onClose={()=>setCollectionDetail(null)}/><div className="collection-promote-actions">{canCreate&&!collectionDetail.product.product_id&&!['queued','processing','unknown'].includes(collectionDetail.product.queue_status||'')&&<button className="shop-button" onClick={()=>{setPromoting(collectionDetail);setCollectionDetail(null)}}>审核并创建正式产品</button>}{collectionDetail.product.source==='1688'&&!collectionDetail.product.product_id&&!collectionDetail.product.queue_status&&<button className="shop-button primary" onClick={()=>void enqueue(collectionDetail)}><Bot size={16}/>加入 Agent 队列</button>}</div></>}
  {promoting&&<CollectionPromotion detail={promoting} close={()=>setPromoting(null)} saved={()=>{setPromoting(null);setNotice('正式产品已创建，可进入 1688 店铺新建发布草稿');void load()}}/>}
  {collectorSetup&&<CollectorSetup onClose={()=>setCollectorSetup(false)} onNotice={setNotice}/>}
  {deletingCollection&&<Confirm title="删除这条采集记录？" text={`“${deletingCollection.title}”及其 SKU 快照将被永久删除。`} action="删除记录" close={()=>setDeletingCollection(null)} confirm={()=>void removeCollection(deletingCollection)}/>}
 </div>
}

function CollectorSetup({onClose,onNotice}:{onClose:()=>void;onNotice:(message:string)=>void}){
 const [key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function generate(){setBusy(true);setError('');try{setKey((await createCollectorKey()).data.key)}catch(cause){setError(cause instanceof Error?cause.message:'生成采集密钥失败。')}finally{setBusy(false)}}
 async function copy(){await navigator.clipboard.writeText(key);onNotice('采集密钥已复制，请粘贴到脚本的 CRM 设置中。')}
 return <div className="dialog-layer"><button className="drawer-scrim" onClick={onClose}/><section className="collector-setup"><header><div><p className="kicker">1688 商品采集</p><h2>配置商品采集器</h2></div><button onClick={onClose}><X size={18}/></button></header><ol><li><b>安装商品采集器</b><span>通过 Tampermonkey 打开并安装完整商品采集脚本。</span><a href={COLLECTOR_SCRIPT_URL} target="_blank" rel="noreferrer">打开脚本 <ExternalLink size={13}/></a></li><li><b>生成专用密钥</b><span>新密钥只显示一次；重新生成会立即吊销旧密钥。</span>{key?<div className="collector-key"><code>{key}</code><button onClick={()=>void copy()}><Copy size={14}/>复制</button></div>:<button className="generate-key" disabled={busy} onClick={()=>void generate()}><KeyRound size={14}/>{busy?'生成中…':'生成采集密钥'}</button>}</li><li><b>直接采集商品</b><span>打开商品详情页，点击右下角采集器，填写 CRM API 地址与密钥，然后点击“采集此商品”；列表页也支持批量采集。</span></li></ol>{error&&<div className="form-error">{error}</div>}</section></div>
}

function CollectionPreview({detail,onClose}:{detail:CollectedProductDetail;onClose:()=>void}){const p=detail.product;return <div className="drawer-layer"><button className="drawer-scrim" onClick={onClose}/><aside className="record-drawer collection-drawer"><header><div><p className="kicker">{p.source} 原始商品</p><h2>{p.title}</h2></div><button onClick={onClose}><X size={20}/></button></header><div className="collection-detail"><div className="collection-hero">{p.main_image_url&&<img src={p.main_image_url} alt="" referrerPolicy="no-referrer"/>}<div><span>源商品 ID</span><b>{p.source_product_id}</b>{p.seller_name&&<small>{p.seller_name}</small>}{p.category_path&&<small>{p.category_path}</small>}<a href={p.source_url} target="_blank" rel="noreferrer">查看源页面 <ExternalLink size={13}/></a></div></div><div className="collection-facts"><span>{p.gallery_images.length} 张主图</span><span>{p.detail_images.length} 张详情图</span><span>{Object.keys(p.attributes).length} 项属性</span>{p.video_url&&<a href={p.video_url} target="_blank" rel="noreferrer">主图视频 <ExternalLink size={12}/></a>}</div><section><div className="section-head"><div><p className="kicker">原始 SKU 快照</p><h3>{detail.variants.length} 个款式</h3></div></div>{detail.variants.length?<div className="variant-list">{detail.variants.map(v=><article key={v.id}>{v.image_url?<img src={v.image_url} alt="" referrerPolicy="no-referrer"/>:<div className="variant-image-empty"><Box size={17}/></div>}<div><b>{v.label}</b><small>{Object.entries(v.attributes).map(([k,val])=>`${k}: ${val}`).join(' · ')||'暂无规格属性'}</small></div><strong>{v.price==null?(v.price_text||'—'):money(v.price)}</strong><span>{v.stock_text||'库存未知'}</span></article>)}</div>:<p className="tier-empty">该来源商品没有独立 SKU 组合，商品级信息已完整保存。</p>}</section></div></aside></div>}

function Confirm({title,text,action,close,confirm}:{title:string;text:string;action:string;close:()=>void;confirm:()=>void}){return <div className="dialog-layer"><button className="drawer-scrim" onClick={close}/><section className="confirm-dialog"><div className="confirm-icon"><Trash2 size={20}/></div><h2>{title}</h2><p>{text}</p><div><button onClick={close}>取消</button><button className="danger" onClick={confirm}>{action}</button></div></section></div>}
